// Package nbi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package nbi

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for ApplicationDeploymentOperation.
const (
	DELETE ApplicationDeploymentOperation = "DELETE"
	DEPLOY ApplicationDeploymentOperation = "DEPLOY"
	UPDATE ApplicationDeploymentOperation = "UPDATE"
)

// Defines values for ApplicationDeploymentOperationStatus.
const (
	ApplicationDeploymentOperationStatusCANCELLED  ApplicationDeploymentOperationStatus = "CANCELLED"
	ApplicationDeploymentOperationStatusCOMPLETED  ApplicationDeploymentOperationStatus = "COMPLETED"
	ApplicationDeploymentOperationStatusFAILED     ApplicationDeploymentOperationStatus = "FAILED"
	ApplicationDeploymentOperationStatusPENDING    ApplicationDeploymentOperationStatus = "PENDING"
	ApplicationDeploymentOperationStatusPROCESSING ApplicationDeploymentOperationStatus = "PROCESSING"
)

// Defines values for ApplicationDeploymentProfileType.
const (
	Compose ApplicationDeploymentProfileType = "compose"
	HelmV3  ApplicationDeploymentProfileType = "helm.v3"
)

// Defines values for ApplicationDeploymentStatusState.
const (
	CRASHLOOP ApplicationDeploymentStatusState = "CRASHLOOP"
	RUNNING   ApplicationDeploymentStatusState = "RUNNING"
	UPDATING  ApplicationDeploymentStatusState = "UPDATING"
)

// Defines values for ApplicationPackageOperation.
const (
	DEBOARD ApplicationPackageOperation = "DEBOARD"
	ONBOARD ApplicationPackageOperation = "ONBOARD"
	STAGE   ApplicationPackageOperation = "STAGE"
	UNSTAGE ApplicationPackageOperation = "UNSTAGE"
)

// Defines values for ApplicationPackageOperationStatus.
const (
	ApplicationPackageOperationStatusCANCELLED  ApplicationPackageOperationStatus = "CANCELLED"
	ApplicationPackageOperationStatusCOMPLETED  ApplicationPackageOperationStatus = "COMPLETED"
	ApplicationPackageOperationStatusFAILED     ApplicationPackageOperationStatus = "FAILED"
	ApplicationPackageOperationStatusPENDING    ApplicationPackageOperationStatus = "PENDING"
	ApplicationPackageOperationStatusPROCESSING ApplicationPackageOperationStatus = "PROCESSING"
)

// Defines values for ApplicationPackageSpecSourceType.
const (
	GITREPO ApplicationPackageSpecSourceType = "GIT_REPO"
)

// Defines values for ApplicationPackageStatusState.
const (
	DEBOARDED ApplicationPackageStatusState = "DEBOARDED"
	FAILED    ApplicationPackageStatusState = "FAILED"
	ONBOARDED ApplicationPackageStatusState = "ONBOARDED"
	PENDING   ApplicationPackageStatusState = "PENDING"
	STAGED    ApplicationPackageStatusState = "STAGED"
	UNSTAGED  ApplicationPackageStatusState = "UNSTAGED"
)

// APIResponse defines model for APIResponse.
type APIResponse struct {
	// RequestId Request identifier
	RequestId string `json:"requestId"`

	// Timestamp Timestamp of the request
	Timestamp time.Time `json:"timestamp"`
}

// ApplicationDeploymentListResp List of Application Deployments
type ApplicationDeploymentListResp struct {
	// ApiVersion API version
	ApiVersion string                      `json:"apiVersion"`
	Items      []ApplicationDeploymentResp `json:"items"`

	// Kind Resource kind
	Kind     string             `json:"kind"`
	Metadata PaginationMetadata `json:"metadata"`
}

// ApplicationDeploymentOperation Current application deployment operation
type ApplicationDeploymentOperation string

// ApplicationDeploymentOperationStatus Current state of the application deployment operation
type ApplicationDeploymentOperationStatus string

// ApplicationDeploymentProfile Application Deployment Profile
type ApplicationDeploymentProfile struct {
	// Components Components of the deployment profile
	Components []ApplicationDeploymentProfile_Components_Item `json:"components"`

	// Type Type of deployment profile
	Type ApplicationDeploymentProfileType `json:"type"`
}

// ApplicationDeploymentProfile_Components_Item defines model for ApplicationDeploymentProfile.components.Item.
type ApplicationDeploymentProfile_Components_Item struct {
	union json.RawMessage
}

// ApplicationDeploymentProfileType Type of deployment profile
type ApplicationDeploymentProfileType string

// ApplicationDeploymentRecentOperation defines model for ApplicationDeploymentRecentOperation.
type ApplicationDeploymentRecentOperation struct {
	// Op Current application deployment operation
	Op ApplicationDeploymentOperation `json:"op"`

	// Status Current state of the application deployment operation
	Status ApplicationDeploymentOperationStatus `json:"status"`
}

// ApplicationDeploymentRequest Application Deployment request
type ApplicationDeploymentRequest struct {
	// ApiVersion API version
	ApiVersion string `json:"apiVersion"`

	// Kind Resource kind
	Kind     string `json:"kind"`
	Metadata struct {
		// Annotations Annotations for the deployment
		Annotations *map[string]string `json:"annotations,omitempty"`

		// CreationTimestamp Creation timestamp
		CreationTimestamp *time.Time `json:"creationTimestamp,omitempty"`

		// Id This field is generated by the server.
		Id *string `json:"id,omitempty"`

		// Labels Labels for the deployment
		Labels *map[string]string `json:"labels,omitempty"`

		// Name Name of the deployment
		Name string `json:"name"`

		// Namespace Namespace of the deployment
		Namespace *string `json:"namespace,omitempty"`
	} `json:"metadata"`

	// Spec Application Deployment specification
	Spec ApplicationDeploymentSpec `json:"spec"`
}

// ApplicationDeploymentResp Application Deployment manifest
type ApplicationDeploymentResp struct {
	// ApiVersion API version
	ApiVersion string `json:"apiVersion"`

	// Kind Resource kind
	Kind            string                             `json:"kind"`
	Metadata        Metadata                           `json:"metadata"`
	RecentOperation *ApplicationPackageRecentOperation `json:"recentOperation,omitempty"`

	// Spec Application Deployment specification
	Spec ApplicationDeploymentSpec `json:"spec"`

	// Status Application Deployment status
	Status *ApplicationDeploymentStatus `json:"status,omitempty"`
}

// ApplicationDeploymentSpec Application Deployment specification
type ApplicationDeploymentSpec struct {
	AppPackageRef struct {
		// Id ID of the ApplicationPackage
		Id string `json:"id"`
	} `json:"appPackageRef"`

	// DeploymentProfile Application Deployment Profile
	DeploymentProfile ApplicationDeploymentProfile         `json:"deploymentProfile"`
	DeviceRef         *ApplicationDeploymentSpec_DeviceRef `json:"deviceRef,omitempty"`

	// Parameters Application Parameters
	Parameters *ApplicationParameters `json:"parameters,omitempty"`
}

// ApplicationDeploymentSpecDeviceRef0 defines model for .
type ApplicationDeploymentSpecDeviceRef0 = interface{}

// ApplicationDeploymentSpecDeviceRef1 defines model for .
type ApplicationDeploymentSpecDeviceRef1 = interface{}

// ApplicationDeploymentSpec_DeviceRef defines model for ApplicationDeploymentSpec.DeviceRef.
type ApplicationDeploymentSpec_DeviceRef struct {
	// Id ID of the Device
	Id *string `json:"id,omitempty"`

	// Labels Labels for the Device
	Labels *map[string]interface{} `json:"labels,omitempty"`
	union  json.RawMessage
}

// ApplicationDeploymentStatus Application Deployment status
type ApplicationDeploymentStatus struct {
	ContextualInfo *ContextualInfo `json:"contextualInfo,omitempty"`

	// LastUpdateTime Last update time
	LastUpdateTime *time.Time `json:"lastUpdateTime,omitempty"`

	// State State of the deployment
	State *ApplicationDeploymentStatusState `json:"state,omitempty"`
}

// ApplicationDeploymentStatusState State of the deployment
type ApplicationDeploymentStatusState string

// ApplicationPackageListResp List of Application Packages
type ApplicationPackageListResp struct {
	// ApiVersion API version
	ApiVersion string                   `json:"apiVersion"`
	Items      []ApplicationPackageResp `json:"items"`
	Kind       string                   `json:"kind"`
	Metadata   *PaginationMetadata      `json:"metadata,omitempty"`
}

// ApplicationPackageOperation Current application package operation
type ApplicationPackageOperation string

// ApplicationPackageOperationStatus Current state of the application package operation
type ApplicationPackageOperationStatus string

// ApplicationPackageRecentOperation defines model for ApplicationPackageRecentOperation.
type ApplicationPackageRecentOperation struct {
	// Op Current application package operation
	Op ApplicationPackageOperation `json:"op"`

	// Status Current state of the application package operation
	Status ApplicationPackageOperationStatus `json:"status"`
}

// ApplicationPackageRequest Application Package manifest
type ApplicationPackageRequest struct {
	// ApiVersion API version
	ApiVersion string `json:"apiVersion"`

	// Kind Resource kind
	Kind     string `json:"kind"`
	Metadata struct {
		// Annotations Annotations for the resource
		Annotations *map[string]string `json:"annotations,omitempty"`

		// Labels Labels for the resource
		Labels *map[string]string `json:"labels,omitempty"`

		// Name Name of the resource
		Name string `json:"name"`

		// Namespace Namespace of the resource
		Namespace *string `json:"namespace,omitempty"`
	} `json:"metadata"`

	// Spec Application Package specification
	Spec ApplicationPackageSpec `json:"spec"`
}

// ApplicationPackageResp Application Package manifest
type ApplicationPackageResp struct {
	// ApiVersion API version
	ApiVersion string `json:"apiVersion"`

	// Kind Resource kind
	Kind            string                             `json:"kind"`
	Metadata        Metadata                           `json:"metadata"`
	RecentOperation *ApplicationPackageRecentOperation `json:"recentOperation,omitempty"`

	// Spec Application Package specification
	Spec   ApplicationPackageSpec    `json:"spec"`
	Status *ApplicationPackageStatus `json:"status,omitempty"`
}

// ApplicationPackageSpec Application Package specification
type ApplicationPackageSpec struct {
	// Source Source configuration based on sourceType
	Source ApplicationPackageSpec_Source `json:"source"`

	// SourceType Type of source for the application package
	SourceType ApplicationPackageSpecSourceType `json:"sourceType"`
}

// ApplicationPackageSpec_Source Source configuration based on sourceType
type ApplicationPackageSpec_Source struct {
	union json.RawMessage
}

// ApplicationPackageSpecSourceType Type of source for the application package
type ApplicationPackageSpecSourceType string

// ApplicationPackageStatus defines model for ApplicationPackageStatus.
type ApplicationPackageStatus struct {
	ContextualInfo *ContextualInfo `json:"contextualInfo,omitempty"`

	// LastUpdateTime Last update time
	LastUpdateTime *time.Time `json:"lastUpdateTime,omitempty"`

	// State State of the application package
	State *ApplicationPackageStatusState `json:"state,omitempty"`
}

// ApplicationPackageStatusState State of the application package
type ApplicationPackageStatusState string

// ApplicationParameterTarget Application Parameter Target
type ApplicationParameterTarget struct {
	// Components Components of the parameter
	Components []string `json:"components"`

	// Pointer Pointer to the parameter
	Pointer string `json:"pointer"`
}

// ApplicationParameterValue Application Parameter Value
type ApplicationParameterValue struct {
	// Targets Targets of the parameter
	Targets []ApplicationParameterTarget `json:"targets"`

	// Value Value of the parameter
	Value string `json:"value"`
}

// ApplicationParameters Application Parameters
type ApplicationParameters map[string]ApplicationParameterValue

// ComposeApplicationDeploymentProfileComponent Compose Application Deployment Profile Component
type ComposeApplicationDeploymentProfileComponent struct {
	// Name Name of the component
	Name       string `json:"name"`
	Properties struct {
		// KeyLocation Key location of the component
		KeyLocation *string `json:"keyLocation,omitempty"`

		// PackageLocation Package location of the component
		PackageLocation string `json:"packageLocation"`

		// Timeout Timeout for the component
		Timeout *string `json:"timeout,omitempty"`

		// Wait Wait for the component to be ready
		Wait *bool `json:"wait,omitempty"`
	} `json:"properties"`
}

// ContextualInfo defines model for ContextualInfo.
type ContextualInfo struct {
	// Code Code of the contextual information
	Code *string `json:"code,omitempty"`

	// Message Message of the contextual information
	Message *string `json:"message,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Details Additional details about the error
	Details *map[string]interface{} `json:"details,omitempty"`

	// ErrorCode Error code
	ErrorCode string `json:"errorCode"`

	// RequestId Request identifier
	RequestId string `json:"requestId"`

	// Timestamp Timestamp of the request
	Timestamp time.Time `json:"timestamp"`
}

// GitRepo Git repository source configuration
type GitRepo struct {
	// AccessToken Git access token for authentication
	AccessToken *string `json:"accessToken,omitempty"`

	// Branch Git branch to use
	Branch *string `json:"branch,omitempty"`

	// SubPath Subdirectory within the repository containing the application description yaml (ex margo.yaml)
	SubPath *string `json:"subPath,omitempty"`

	// Tag Git tag to use (alternative to branch)
	Tag *string `json:"tag,omitempty"`

	// Url Git repository URL (only HTTPS is supported)
	Url string `json:"url"`

	// Username Git username for authentication
	Username *string `json:"username,omitempty"`
	union    json.RawMessage
}

// GitRepo0 defines model for .
type GitRepo0 = interface{}

// GitRepo1 defines model for .
type GitRepo1 = interface{}

// HelmApplicationDeploymentProfileComponent Helm Application Deployment Profile Component
type HelmApplicationDeploymentProfileComponent struct {
	// Name Name of the component
	Name       string `json:"name"`
	Properties struct {
		// Repository Repository of the component
		Repository string `json:"repository"`

		// Revision Revision of the component
		Revision *string `json:"revision,omitempty"`

		// Timeout Timeout for the component
		Timeout *string `json:"timeout,omitempty"`

		// Wait Wait for the component to be ready
		Wait *bool `json:"wait,omitempty"`
	} `json:"properties"`
}

// Metadata defines model for Metadata.
type Metadata struct {
	// Annotations Annotations for the resource
	Annotations *map[string]string `json:"annotations,omitempty"`

	// CreationTimestamp Creation timestamp
	CreationTimestamp *time.Time `json:"creationTimestamp,omitempty"`

	// Id This field is generated by the server.
	Id *string `json:"id,omitempty"`

	// Labels Labels for the resource
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Name of the resource
	Name string `json:"name"`

	// Namespace Namespace of the resource
	Namespace *string `json:"namespace,omitempty"`
}

// PaginationMetadata defines model for PaginationMetadata.
type PaginationMetadata struct {
	// Continue Indicates if there are more items to retrieve
	Continue *bool `json:"continue,omitempty"`

	// RemainingItemCount Number of items remaining
	RemainingItemCount *int `json:"remainingItemCount,omitempty"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	// Field Field with the validation error
	Field string `json:"field"`

	// Message Validation error message
	Message string `json:"message"`
}

// ListApplicationDeploymentsParams defines parameters for ListApplicationDeployments.
type ListApplicationDeploymentsParams struct {
	// Limit Maximum number of items to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Continue Token for pagination
	Continue *string `form:"continue,omitempty" json:"continue,omitempty"`
}

// ListAppPackagesParams defines parameters for ListAppPackages.
type ListAppPackagesParams struct {
	// Limit Maximum number of items to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Continue Token for pagination
	Continue *string `form:"continue,omitempty" json:"continue,omitempty"`
}

// DeleteAppPackageParams defines parameters for DeleteAppPackage.
type DeleteAppPackageParams struct {
	// Force Force deletion even if in use
	Force *bool `form:"force,omitempty" json:"force,omitempty"`
}

// CreateApplicationDeploymentJSONRequestBody defines body for CreateApplicationDeployment for application/json ContentType.
type CreateApplicationDeploymentJSONRequestBody = ApplicationDeploymentRequest

// OnboardAppPackageJSONRequestBody defines body for OnboardAppPackage for application/json ContentType.
type OnboardAppPackageJSONRequestBody = ApplicationPackageRequest

// AsHelmApplicationDeploymentProfileComponent returns the union data inside the ApplicationDeploymentProfile_Components_Item as a HelmApplicationDeploymentProfileComponent
func (t ApplicationDeploymentProfile_Components_Item) AsHelmApplicationDeploymentProfileComponent() (HelmApplicationDeploymentProfileComponent, error) {
	var body HelmApplicationDeploymentProfileComponent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromHelmApplicationDeploymentProfileComponent overwrites any union data inside the ApplicationDeploymentProfile_Components_Item as the provided HelmApplicationDeploymentProfileComponent
func (t *ApplicationDeploymentProfile_Components_Item) FromHelmApplicationDeploymentProfileComponent(v HelmApplicationDeploymentProfileComponent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeHelmApplicationDeploymentProfileComponent performs a merge with any union data inside the ApplicationDeploymentProfile_Components_Item, using the provided HelmApplicationDeploymentProfileComponent
func (t *ApplicationDeploymentProfile_Components_Item) MergeHelmApplicationDeploymentProfileComponent(v HelmApplicationDeploymentProfileComponent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsComposeApplicationDeploymentProfileComponent returns the union data inside the ApplicationDeploymentProfile_Components_Item as a ComposeApplicationDeploymentProfileComponent
func (t ApplicationDeploymentProfile_Components_Item) AsComposeApplicationDeploymentProfileComponent() (ComposeApplicationDeploymentProfileComponent, error) {
	var body ComposeApplicationDeploymentProfileComponent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromComposeApplicationDeploymentProfileComponent overwrites any union data inside the ApplicationDeploymentProfile_Components_Item as the provided ComposeApplicationDeploymentProfileComponent
func (t *ApplicationDeploymentProfile_Components_Item) FromComposeApplicationDeploymentProfileComponent(v ComposeApplicationDeploymentProfileComponent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeComposeApplicationDeploymentProfileComponent performs a merge with any union data inside the ApplicationDeploymentProfile_Components_Item, using the provided ComposeApplicationDeploymentProfileComponent
func (t *ApplicationDeploymentProfile_Components_Item) MergeComposeApplicationDeploymentProfileComponent(v ComposeApplicationDeploymentProfileComponent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t ApplicationDeploymentProfile_Components_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ApplicationDeploymentProfile_Components_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsApplicationDeploymentSpecDeviceRef0 returns the union data inside the ApplicationDeploymentSpec_DeviceRef as a ApplicationDeploymentSpecDeviceRef0
func (t ApplicationDeploymentSpec_DeviceRef) AsApplicationDeploymentSpecDeviceRef0() (ApplicationDeploymentSpecDeviceRef0, error) {
	var body ApplicationDeploymentSpecDeviceRef0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApplicationDeploymentSpecDeviceRef0 overwrites any union data inside the ApplicationDeploymentSpec_DeviceRef as the provided ApplicationDeploymentSpecDeviceRef0
func (t *ApplicationDeploymentSpec_DeviceRef) FromApplicationDeploymentSpecDeviceRef0(v ApplicationDeploymentSpecDeviceRef0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeApplicationDeploymentSpecDeviceRef0 performs a merge with any union data inside the ApplicationDeploymentSpec_DeviceRef, using the provided ApplicationDeploymentSpecDeviceRef0
func (t *ApplicationDeploymentSpec_DeviceRef) MergeApplicationDeploymentSpecDeviceRef0(v ApplicationDeploymentSpecDeviceRef0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsApplicationDeploymentSpecDeviceRef1 returns the union data inside the ApplicationDeploymentSpec_DeviceRef as a ApplicationDeploymentSpecDeviceRef1
func (t ApplicationDeploymentSpec_DeviceRef) AsApplicationDeploymentSpecDeviceRef1() (ApplicationDeploymentSpecDeviceRef1, error) {
	var body ApplicationDeploymentSpecDeviceRef1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApplicationDeploymentSpecDeviceRef1 overwrites any union data inside the ApplicationDeploymentSpec_DeviceRef as the provided ApplicationDeploymentSpecDeviceRef1
func (t *ApplicationDeploymentSpec_DeviceRef) FromApplicationDeploymentSpecDeviceRef1(v ApplicationDeploymentSpecDeviceRef1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeApplicationDeploymentSpecDeviceRef1 performs a merge with any union data inside the ApplicationDeploymentSpec_DeviceRef, using the provided ApplicationDeploymentSpecDeviceRef1
func (t *ApplicationDeploymentSpec_DeviceRef) MergeApplicationDeploymentSpecDeviceRef1(v ApplicationDeploymentSpecDeviceRef1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t ApplicationDeploymentSpec_DeviceRef) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.Id != nil {
		object["id"], err = json.Marshal(t.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if t.Labels != nil {
		object["labels"], err = json.Marshal(t.Labels)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'labels': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *ApplicationDeploymentSpec_DeviceRef) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &t.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
	}

	if raw, found := object["labels"]; found {
		err = json.Unmarshal(raw, &t.Labels)
		if err != nil {
			return fmt.Errorf("error reading 'labels': %w", err)
		}
	}

	return err
}

// AsGitRepo returns the union data inside the ApplicationPackageSpec_Source as a GitRepo
func (t ApplicationPackageSpec_Source) AsGitRepo() (GitRepo, error) {
	var body GitRepo
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGitRepo overwrites any union data inside the ApplicationPackageSpec_Source as the provided GitRepo
func (t *ApplicationPackageSpec_Source) FromGitRepo(v GitRepo) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGitRepo performs a merge with any union data inside the ApplicationPackageSpec_Source, using the provided GitRepo
func (t *ApplicationPackageSpec_Source) MergeGitRepo(v GitRepo) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t ApplicationPackageSpec_Source) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ApplicationPackageSpec_Source) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsGitRepo0 returns the union data inside the GitRepo as a GitRepo0
func (t GitRepo) AsGitRepo0() (GitRepo0, error) {
	var body GitRepo0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGitRepo0 overwrites any union data inside the GitRepo as the provided GitRepo0
func (t *GitRepo) FromGitRepo0(v GitRepo0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGitRepo0 performs a merge with any union data inside the GitRepo, using the provided GitRepo0
func (t *GitRepo) MergeGitRepo0(v GitRepo0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsGitRepo1 returns the union data inside the GitRepo as a GitRepo1
func (t GitRepo) AsGitRepo1() (GitRepo1, error) {
	var body GitRepo1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGitRepo1 overwrites any union data inside the GitRepo as the provided GitRepo1
func (t *GitRepo) FromGitRepo1(v GitRepo1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGitRepo1 performs a merge with any union data inside the GitRepo, using the provided GitRepo1
func (t *GitRepo) MergeGitRepo1(v GitRepo1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t GitRepo) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.AccessToken != nil {
		object["accessToken"], err = json.Marshal(t.AccessToken)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'accessToken': %w", err)
		}
	}

	if t.Branch != nil {
		object["branch"], err = json.Marshal(t.Branch)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'branch': %w", err)
		}
	}

	if t.SubPath != nil {
		object["subPath"], err = json.Marshal(t.SubPath)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'subPath': %w", err)
		}
	}

	if t.Tag != nil {
		object["tag"], err = json.Marshal(t.Tag)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'tag': %w", err)
		}
	}

	object["url"], err = json.Marshal(t.Url)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'url': %w", err)
	}

	if t.Username != nil {
		object["username"], err = json.Marshal(t.Username)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'username': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *GitRepo) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["accessToken"]; found {
		err = json.Unmarshal(raw, &t.AccessToken)
		if err != nil {
			return fmt.Errorf("error reading 'accessToken': %w", err)
		}
	}

	if raw, found := object["branch"]; found {
		err = json.Unmarshal(raw, &t.Branch)
		if err != nil {
			return fmt.Errorf("error reading 'branch': %w", err)
		}
	}

	if raw, found := object["subPath"]; found {
		err = json.Unmarshal(raw, &t.SubPath)
		if err != nil {
			return fmt.Errorf("error reading 'subPath': %w", err)
		}
	}

	if raw, found := object["tag"]; found {
		err = json.Unmarshal(raw, &t.Tag)
		if err != nil {
			return fmt.Errorf("error reading 'tag': %w", err)
		}
	}

	if raw, found := object["url"]; found {
		err = json.Unmarshal(raw, &t.Url)
		if err != nil {
			return fmt.Errorf("error reading 'url': %w", err)
		}
	}

	if raw, found := object["username"]; found {
		err = json.Unmarshal(raw, &t.Username)
		if err != nil {
			return fmt.Errorf("error reading 'username': %w", err)
		}
	}

	return err
}
