// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package client

import . "github.com/margo/dev-repo/sdk/api/wfm/northbound/models"

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListAppPkgs request
	ListAppPkgs(ctx context.Context, params *ListAppPkgsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OnboardAppPkgWithBody request with any body
	OnboardAppPkgWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	OnboardAppPkg(ctx context.Context, body OnboardAppPkgJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteAppPkg request
	DeleteAppPkg(ctx context.Context, id string, params *DeleteAppPkgParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAppPkg request
	GetAppPkg(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListAppPkgs(ctx context.Context, params *ListAppPkgsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListAppPkgsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OnboardAppPkgWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOnboardAppPkgRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OnboardAppPkg(ctx context.Context, body OnboardAppPkgJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOnboardAppPkgRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteAppPkg(ctx context.Context, id string, params *DeleteAppPkgParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteAppPkgRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAppPkg(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAppPkgRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListAppPkgsRequest generates requests for ListAppPkgs
func NewListAppPkgsRequest(server string, params *ListAppPkgsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/app-pkgs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page", runtime.ParamLocationQuery, *params.Page); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "pageSize", runtime.ParamLocationQuery, *params.PageSize); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewOnboardAppPkgRequest calls the generic OnboardAppPkg builder with application/json body
func NewOnboardAppPkgRequest(server string, body OnboardAppPkgJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewOnboardAppPkgRequestWithBody(server, "application/json", bodyReader)
}

// NewOnboardAppPkgRequestWithBody generates requests for OnboardAppPkg with any type of body
func NewOnboardAppPkgRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/app-pkgs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteAppPkgRequest generates requests for DeleteAppPkg
func NewDeleteAppPkgRequest(server string, id string, params *DeleteAppPkgParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/app-pkgs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Force != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "force", runtime.ParamLocationQuery, *params.Force); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAppPkgRequest generates requests for GetAppPkg
func NewGetAppPkgRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/app-pkgs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListAppPkgsWithResponse request
	ListAppPkgsWithResponse(ctx context.Context, params *ListAppPkgsParams, reqEditors ...RequestEditorFn) (*ListAppPkgsResponse, error)

	// OnboardAppPkgWithBodyWithResponse request with any body
	OnboardAppPkgWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OnboardAppPkgResponse, error)

	OnboardAppPkgWithResponse(ctx context.Context, body OnboardAppPkgJSONRequestBody, reqEditors ...RequestEditorFn) (*OnboardAppPkgResponse, error)

	// DeleteAppPkgWithResponse request
	DeleteAppPkgWithResponse(ctx context.Context, id string, params *DeleteAppPkgParams, reqEditors ...RequestEditorFn) (*DeleteAppPkgResponse, error)

	// GetAppPkgWithResponse request
	GetAppPkgWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetAppPkgResponse, error)
}

type ListAppPkgsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data *ListAppPkgsResp `json:"data,omitempty"`

		// RequestId Unique identifier for the request
		RequestId string `json:"requestId"`

		// Timestamp Timestamp of the response in ISO 8601 format
		Timestamp time.Time `json:"timestamp"`
	}
	JSON400 *ErrorResponse
	JSON500 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ListAppPkgsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListAppPkgsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type OnboardAppPkgResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *struct {
		Data *AppPkgOnboardingResp `json:"data,omitempty"`

		// RequestId Unique identifier for the request
		RequestId string `json:"requestId"`

		// Timestamp Timestamp of the response in ISO 8601 format
		Timestamp time.Time `json:"timestamp"`
	}
	JSON400 *ErrorResponse
	JSON409 *ErrorResponse
	JSON422 *struct {
		// Details Additional error details
		Details *map[string]interface{} `json:"details,omitempty"`

		// ErrorCode Machine-readable error code
		ErrorCode string `json:"errorCode"`

		// RequestId Unique identifier for the request
		RequestId string `json:"requestId"`

		// Timestamp Timestamp of the response in ISO 8601 format
		Timestamp        time.Time          `json:"timestamp"`
		ValidationErrors *[]ValidationError `json:"validationErrors,omitempty"`
	}
	JSON500 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r OnboardAppPkgResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OnboardAppPkgResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteAppPkgResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *struct {
		Data *DeleteAppPkgResp `json:"data,omitempty"`

		// RequestId Unique identifier for the request
		RequestId string `json:"requestId"`

		// Timestamp Timestamp of the response in ISO 8601 format
		Timestamp time.Time `json:"timestamp"`
	}
	JSON400 *ErrorResponse
	JSON404 *ErrorResponse
	JSON409 *struct {
		// ConflictReason Detailed reason for the conflict
		ConflictReason *string `json:"conflictReason,omitempty"`

		// Details Additional error details
		Details *map[string]interface{} `json:"details,omitempty"`

		// ErrorCode Machine-readable error code
		ErrorCode string `json:"errorCode"`

		// RequestId Unique identifier for the request
		RequestId string `json:"requestId"`

		// Timestamp Timestamp of the response in ISO 8601 format
		Timestamp time.Time `json:"timestamp"`
	}
	JSON500 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteAppPkgResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteAppPkgResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAppPkgResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data *AppPkgSummary `json:"data,omitempty"`

		// RequestId Unique identifier for the request
		RequestId string `json:"requestId"`

		// Timestamp Timestamp of the response in ISO 8601 format
		Timestamp time.Time `json:"timestamp"`
	}
	JSON404 *ErrorResponse
	JSON500 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetAppPkgResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAppPkgResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListAppPkgsWithResponse request returning *ListAppPkgsResponse
func (c *ClientWithResponses) ListAppPkgsWithResponse(ctx context.Context, params *ListAppPkgsParams, reqEditors ...RequestEditorFn) (*ListAppPkgsResponse, error) {
	rsp, err := c.ListAppPkgs(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListAppPkgsResponse(rsp)
}

// OnboardAppPkgWithBodyWithResponse request with arbitrary body returning *OnboardAppPkgResponse
func (c *ClientWithResponses) OnboardAppPkgWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OnboardAppPkgResponse, error) {
	rsp, err := c.OnboardAppPkgWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOnboardAppPkgResponse(rsp)
}

func (c *ClientWithResponses) OnboardAppPkgWithResponse(ctx context.Context, body OnboardAppPkgJSONRequestBody, reqEditors ...RequestEditorFn) (*OnboardAppPkgResponse, error) {
	rsp, err := c.OnboardAppPkg(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOnboardAppPkgResponse(rsp)
}

// DeleteAppPkgWithResponse request returning *DeleteAppPkgResponse
func (c *ClientWithResponses) DeleteAppPkgWithResponse(ctx context.Context, id string, params *DeleteAppPkgParams, reqEditors ...RequestEditorFn) (*DeleteAppPkgResponse, error) {
	rsp, err := c.DeleteAppPkg(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteAppPkgResponse(rsp)
}

// GetAppPkgWithResponse request returning *GetAppPkgResponse
func (c *ClientWithResponses) GetAppPkgWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetAppPkgResponse, error) {
	rsp, err := c.GetAppPkg(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAppPkgResponse(rsp)
}

// ParseListAppPkgsResponse parses an HTTP response from a ListAppPkgsWithResponse call
func ParseListAppPkgsResponse(rsp *http.Response) (*ListAppPkgsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListAppPkgsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data *ListAppPkgsResp `json:"data,omitempty"`

			// RequestId Unique identifier for the request
			RequestId string `json:"requestId"`

			// Timestamp Timestamp of the response in ISO 8601 format
			Timestamp time.Time `json:"timestamp"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseOnboardAppPkgResponse parses an HTTP response from a OnboardAppPkgWithResponse call
func ParseOnboardAppPkgResponse(rsp *http.Response) (*OnboardAppPkgResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OnboardAppPkgResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest struct {
			Data *AppPkgOnboardingResp `json:"data,omitempty"`

			// RequestId Unique identifier for the request
			RequestId string `json:"requestId"`

			// Timestamp Timestamp of the response in ISO 8601 format
			Timestamp time.Time `json:"timestamp"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			// Details Additional error details
			Details *map[string]interface{} `json:"details,omitempty"`

			// ErrorCode Machine-readable error code
			ErrorCode string `json:"errorCode"`

			// RequestId Unique identifier for the request
			RequestId string `json:"requestId"`

			// Timestamp Timestamp of the response in ISO 8601 format
			Timestamp        time.Time          `json:"timestamp"`
			ValidationErrors *[]ValidationError `json:"validationErrors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteAppPkgResponse parses an HTTP response from a DeleteAppPkgWithResponse call
func ParseDeleteAppPkgResponse(rsp *http.Response) (*DeleteAppPkgResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteAppPkgResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest struct {
			Data *DeleteAppPkgResp `json:"data,omitempty"`

			// RequestId Unique identifier for the request
			RequestId string `json:"requestId"`

			// Timestamp Timestamp of the response in ISO 8601 format
			Timestamp time.Time `json:"timestamp"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest struct {
			// ConflictReason Detailed reason for the conflict
			ConflictReason *string `json:"conflictReason,omitempty"`

			// Details Additional error details
			Details *map[string]interface{} `json:"details,omitempty"`

			// ErrorCode Machine-readable error code
			ErrorCode string `json:"errorCode"`

			// RequestId Unique identifier for the request
			RequestId string `json:"requestId"`

			// Timestamp Timestamp of the response in ISO 8601 format
			Timestamp time.Time `json:"timestamp"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetAppPkgResponse parses an HTTP response from a GetAppPkgWithResponse call
func ParseGetAppPkgResponse(rsp *http.Response) (*GetAppPkgResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAppPkgResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data *AppPkgSummary `json:"data,omitempty"`

			// RequestId Unique identifier for the request
			RequestId string `json:"requestId"`

			// Timestamp Timestamp of the response in ISO 8601 format
			Timestamp time.Time `json:"timestamp"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
