openapi: 3.0.4
info:
  title: MARGO Device APIs - OpenAPI 3.0
  description: |-
    This is draft implementation of the MARGO APIs.
    For the general Lexicon, please refer - [Terminology](https://specification.margo.org/margo-overview/technical-lexicon/#technical-terms) 
    The public definition is provided in [Here](https://specification.margo.org/margo-api-reference/margo-api-specification/) 
    
    Some useful links:
    - TBD -- Fix this [MARGO Device API](https://specification.margo.org/margo-api-reference/workload-api/desired-state-api/desired-state/)
    - [MARGO Authorization](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
  termsOfService: https://specification.margo.org/#an-edge-interoperability-user-story
  contact:
    email: ajcraig@rockwellautomation.com
  license:
    name: MARGO License
    url: https://github.com/margo/specification?#licenses
  version: 0.0.1
externalDocs:
  description: Find out more about MARGO
  url: https://margo.org/
servers:
  - url: https://margo.swagger.io/api/v0
tags:
  - name: device
    description: A MARGO compliant device
    externalDocs:
      description: See Documentation
      url: https://specification.margo.org/margo-overview/technical-lexicon/#technical-terms
paths:
  /device/poke:
    post:
      tags:
        - device
      summary: WFM sends this API to the Device to initiate a state request or a rmote procedure.
      description: WFM sends this API to the Device to initiate a state request or a rmote procedure.
      operationId: poke
      parameters:
        - name: deviceId
          in: query
          description: Device Identifier
          required: true
          explode: true
          schema:
            type: string
            example: Marseilles-Press-ProdCell-15
        - name: rpcId
          in: query
          description: In case the WFM wanted to initiate a Remote Procedure
          required: false
          explode: true
          schema:
            type: string
            example: 
              - proc-112
              - somePrivateProcedure
              - 12345
      responses:
        '200':
          description: Successful operation, Device will send a Current State update
        '400':
          description: Invalid Device ID supplied
        '404':
          description: Device not found
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

      security:
        - margo_auth:
            - write:state
            - read:state                

components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
  
  securitySchemes:
    margo_auth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://margo.swagger.io/oauth/authorize'
          scopes:
            "write:state": modify app state in your device
            "read:state": read your app states
    api_key:
      type: apiKey
      name: api_key
      in: header