openapi: 3.0.4
info:
  title: MARGO Application Desired State - OpenAPI 3.0
  description: |-
    This is draft implementation of the MARGO APIs.
    For the general Lexicon, please refer - [Terminology](https://specification.margo.org/margo-overview/technical-lexicon/#technical-terms) 
    The public definition is provided in [Here](https://specification.margo.org/margo-api-reference/margo-api-specification/) 
    
    Some useful links:
    - [MARGO Desired State](https://specification.margo.org/margo-api-reference/workload-api/desired-state-api/desired-state/)
    - [MARGO Authorization](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
  termsOfService: https://specification.margo.org/#an-edge-interoperability-user-story
  contact:
    email: ajcraig@rockwellautomation.com
  license:
    name: MARGO License
    url: https://github.com/margo/specification?#licenses
  version: 0.0.1
externalDocs:
  description: Find out more about MARGO
  url: https://margo.org/
servers:
  - url: https://margo.swagger.io/api/v0
tags:
  - name: wfm
    description: A MARGO Compliant Workload Fleet Manager
    externalDocs:
      description: See Documentation
      url: https://specification.margo.org/margo-overview/technical-lexicon/#technical-terms
paths:
  /wfm/state:
    post:
      tags:
        - wfm
      summary: Device sends this API to the WFM to update the current-state of the device and applications.
      description: Device sends this API to the WFM to update the current-state of the device and applications.
      operationId: state
      requestBody:
        description: The current-state of the device as well as the state of each deployed app
        content:
            application/json:
              schema:
                $ref: '#/components/schemas/currentAppStates'
      responses:
        '200':
          description: Successful operation, WFM returns desired state of Applications
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/desiredAppStates'
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - margo_auth:
            - write:state
            - read:state
  /wfm/process:
    post:
      tags:
        - wfm
      summary: Device sends this API to the WFM after it's poked with a private RPC Id.
      description: Device sends this API to the WFM after it's poked with a private RPC Id.
      operationId: process
      requestBody:
        description: Send a private payload, not defined by MARGO
        content:
            application/json:
              schema:
                $ref: '#/components/schemas/privatePayload'
      parameters:
        - name: rpcId
          in: query
          description: An RPC call to the WFM, initiated by the Device
          required: false
          explode: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation, WFM returns a private payload not defined by MARGO
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/privatePayload'
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - margo_auth:
            - write:state
            - read:state            
components:
  schemas:
    appDeploymentMetadata:
      type: object
      required: [name]
      properties:
        id:
          type: string
          description: Unique identifier for the application deployment
        name:
          type: string
          description: Name of the resource
        namespace:
          type: string
          description: Namespace of the resource
        labels:
          type: object
          additionalProperties: { type: string }
          description: Labels for the resource
        annotations:
          type: object
          additionalProperties: { type: string }
          description: Annotations for the resource
    helmApplicationDeploymentProfileComponent:
      type: object
      description: Helm Application Deployment Profile Component
      required: [name, properties]
      properties:
        name:
          type: string
          description: Name of the component
        properties:
          type: object
          required: [repository]
          properties:
            repository:
              type: string
              description: Repository of the component
            revision:
              type: string
              description: Revision of the component
            timeout:
              type: string
              description: Timeout for the component
            wait:
              type: boolean
              description: Wait for the component to be ready
    composeApplicationDeploymentProfileComponent:
      type: object
      description: Compose Application Deployment Profile Component
      required: [name, properties]
      properties:
        name:
          type: string
          description: Name of the component
        properties:
          type: object
          required: [packageLocation]
          properties:
            packageLocation:
              type: string
              description: Package location of the component
            keyLocation:
              type: string
              description: Key location of the component
            timeout:
              type: string
              description: Timeout for the component
            wait:
              type: boolean
              description: Wait for the component to be ready
    appDeploymentProfile:
      type: object
      description: Application Deployment Profile
      required: [type, components]
      properties:
        type:
          type: string
          enum: ["helm.v3", "compose"]
          description: Type of deployment profile
        components:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/helmApplicationDeploymentProfileComponent'
              - $ref: '#/components/schemas/composeApplicationDeploymentProfileComponent'
          description: Components of the deployment profile
    appParameterTarget:
      type: object
      description: Application Parameter Target
      required: [pointer, components]
      properties:
        pointer:
          type: string
          description: Pointer to the parameter
        components:
          type: array
          items:
            type: string
          description: Components of the parameter
    appParameterValue:
      type: object
      description: Application Parameter Value
      required: [value, targets]
      properties:
        value:
          type: string
          description: Value of the parameter
        targets:
          type: array
          items:
            $ref: '#/components/schemas/appParameterTarget'
          description: Targets of the parameter
    appDeploymentParams:
      type: object
      description: Application Parameters
      additionalProperties:
        $ref: '#/components/schemas/appParameterValue'
    appDeploymentSpec:
      type: object
      description: Application Deployment specification
      required: [appPackageRef, deploymentProfile]
      properties:
        deploymentProfile:
          $ref: '#/components/schemas/appDeploymentProfile'
          description: Deployment profile
        parameters:
          $ref: '#/components/schemas/appDeploymentParams'
          description: Parameters for the deployment
    appDeployment:
      type: object
      description: Application Deployment manifest
      required: [apiVersion, kind, metadata, spec]
      properties:
        apiVersion:
          type: string
          default: margo.org
          description: API version
        kind:
          type: string
          default: ApplicationDeployment
          description: Resource kind
        metadata:
          $ref: '#/components/schemas/appDeploymentMetadata'
        spec:
          $ref: '#/components/schemas/appDeploymentSpec'
    currentAppStates:
      type: array
      items:
        $ref: '#/components/schemas/appState'
      xml:
        name: currentAppStates
    desiredAppStates:
      type: array
      items:
        $ref: '#/components/schemas/appState'
      xml:
        name: desiredAppStates        
    appState:
      type: object
      properties:
        appId:
          type: string
          example: a12nub7ub
        appVersion:
          type: string
          description: Version String
          example: v1.2.0
        appDeploymentYAML:
          type: string
          description: Base64 encoded MARGO ApplicationDescription YAML content
          example: a2V5MTogdmFsdWUxCmtleTI6IHZhbHVlMgo=
        appDeploymentYAMLHash:
          type: string
          description: App Hash encoding used for versioning the MARGO ApplicationDescription
          example: c6779ec2960296ed9a04f08d67f64422
        appState:
          type: string
          default: STOPPED
          enum:
            - RUNNING
            - UPDATING
            - CRASHLOOP
            - STOPPED
            - REMOVE
      required:
        - appId
        - appVersion
        - appDeploymentYAMLHash
        - appState
      xml:
        name: appCurrentState
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    privatePayload:
      type: object
      properties:
        code:
          type: string
  requestBodies:
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              type: string
  securitySchemes:
    margo_auth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://margo.swagger.io/oauth/authorize'
          scopes:
            "write:state": modify app state in your device
            "read:state": read your app states
    api_key:
      type: apiKey
      name: api_key
      in: header