name: "Task"
description: "An implementable task based on a Story definition"
title: "[TASK: ]"
labels: ["DRAFT"]
assignees:
  - "vireshnavalli"
body:
  - type: markdown
    attributes:
      value: |
         Describe the Task. This may be to do a design, prototype, test or documentation.  
         Ideally a task should be something that can be handled by an individual within a 5-6 story-points in size.
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Describe the Task" 
      placeholder: "Objective, Desired Outcome, Desired artifact updates"
    validations:
      required: true
  - type: input
    id: raisedby
    attributes:
      label: "Raised by (email-id)"
      description: "How can we get in touch with you if we need more info?"
      placeholder: "ex.email@example.com"
    validations:
      required: false
  - type: dropdown
    id: type
    attributes:
      label: Type of Story
      description: "Is this an Story for feature implementation / prototyping / learning ?"
      options:
        - Implementation
        - Prototyping
        - Learning
      default: 0
    validations:
      required: true
  - type: textarea
    id: related
    attributes:
      label: "Related Tasks" 
      description: "Which other tasks does this issue relate to, other than the parent Story"
      placeholder: "GitHub issue #1234 or None"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Describe the "Definition of Done", which can be presented or reviewed
        * The required technical documentation should be updated
        * In case of any prototyping activity, the evaluation, design and outcomes need to be documented 
        * API updates need to be updated in swagger (or other) files
        * Test automation should be done to demonstrate the use-case
        * Code and documentation should be pulled into the release branch and the pull-request approved by the TWG
  - type: dropdown
    id: status
    attributes:
      label: "Status"
      description: "Current status of task" 
      options:
        - Not Started
        - In Motion
        - Under Review
        - Accepted
      default: 0 
  - type: input
    id: "percent_done"
    attributes:
      label: "% Done"
      description: "% Done"
      placeholder: "0"
    validations:
      required: true
  - type: input
    id: storypoints
    attributes:
      label: "Estimated Story-points"
      description: "Estimated days per person needed to implement this Story"
      placeholder: "0"
    validations:
      required: true
  - type: checkboxes
    id: updated_artifacts
    attributes:
      label: "Updated artifacts"
      description: "What all artifacts are updated" 
      options:
        - label: "API Documentation (Swagger)"
          required: false
        - label: "User Docmentation"
          required: false
        - label: "Reference Implementation Code"
          required: false
        - label: "Test Automation"
          required: false
