name: "Story"
description: "A higher level Story mapping to a one or more Epics from TWG"
title: "[Story: ]"
labels: ["DRAFT"]
assignees:
  - "nilanjan-samajdar"
body:
  - type: markdown
    attributes:
      value: |
         Describe the use-case to be implemented from the user-persona point of view. 
         There can be multiple workflows which achieve the use-case
  - type: textarea
    id: description
    attributes:
      label: "Describe the use-case to be implemented, use the MARGO defined Personas to describe the use-case"
      description: "Describe the use-case to be implemented, use the MARGO defined Personas to describe the use-case" 
      placeholder: "Describe the use-case to be implemented, use the MARGO defined Personas to describe the use-case"
    validations:
      required: true
  - type: input
    id: raisedby
    attributes:
      label: "email-id"
      description: "How can we get in touch with you if we need more info?"
      placeholder: "ex.email@example.com"
    validations:
      required: false
  - type: dropdown
    id: type
    attributes:
      label: type
      description: "Is this an Story for feature implementation / prototyping / learning ?"
      options:
        - Implementation
        - Prototyping
        - Learning
      default: 0
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: "related product requirements" 
      description: "Which PM requirements in Github will this Story fulfill ?"
      placeholder: "Requirement-Id"
    validations:
      required: true
  - type: markdown
    attributes:

      value: |
        "Describe the "Definition of Done", which might be a use-case demonstrated to the TWG
        * The required technical documentation should be updated
        * In case of any prototyping activity, the evaluation, design and outcomes need to be documented 
        * API updates need to be updated in swagger (or other) files
        * Test automation should be done to demonstrate the use-case
        * Code and documentation should be pulled into the release branch and the pull-request approved by the TWG"
  - type: textarea
    id: done
    attributes:
      label: "Definition of Done"
      description: "Describe the Definition of Done, which might be a use-case demonstrated to the TWG"
      placeholder: |
        "* The required technical documentation should be updated
         * In case of any prototyping activity, the evaluation, design and outcomes need to be documented 
         * API updates need to be updated in swagger (or other) files
         * Test automation should be done to demonstrate the use-case
         * Code and documentation should be pulled into the release branch and the pull-request approved by the TWG""
    validations:
      required: true
  - type: input
    id: storypoints
    attributes:
      label: "story-points"
      description: "Estimated days per person needed to implement this Story"
      placeholder: "0"
    validations:
      required: true
  - type: checkboxes
    id: impact
    attributes:
      label: "Impacted artifacts"
      description: "What all artifacts are impacted ?" 
      options:
        - label: "API Documentation (Swagger)"
          required: false
        - label: "Design"
          required: false
        - label: "Reference Implementation Code"
          required: false
        - label: "Test Automation"
          required: false
