name: "Feedback"
description: "An open feedback form for the Margo Code First Sandbox"
title: "[FB: ]"
labels: ["DRAFT","Feedback"]
assignees:
  - "nilanjan-samajdar"
body:
  - type: dropdown
    id: feedback_type
    attributes:
      label: Feedback Type
      description: Please select the relevant option
      options:
        - Bug/Issue 
        - New enhancement request
        - Documentation/Content edit request
      default: 0
  - type: markdown
    attributes:
      value: |
         Please provide full details regarding your feedback towards the Code First sandbox below.
         If referring to specific files in documentation or code, please provide file-name and line-number.
  - type: textarea
    id: feedback
    attributes:
      label: "Feedback"
      description: "Feedback" 
      placeholder: "I sense a disturbance in the logic—care to bring balance with your review?"
    validations:
      required: true
