// Package nbi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package nbi

const (
	Margo_authScopes = "margo_auth.Scopes"
)

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// PokeParams defines parameters for Poke.
type PokeParams struct {
	// DeviceId Device Identifier
	DeviceId string `form:"deviceId" json:"deviceId"`

	// RpcId In case the WFM wanted to initiate a Remote Procedure
	RpcId *string `form:"rpcId,omitempty" json:"rpcId,omitempty"`
}
