// Package sbi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package sbi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostClientClientIdCapabilitiesWithBody request with any body
	PostClientClientIdCapabilitiesWithBody(ctx context.Context, clientId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostClientClientIdCapabilities(ctx context.Context, clientId string, body PostClientClientIdCapabilitiesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutClientClientIdCapabilitiesWithBody request with any body
	PutClientClientIdCapabilitiesWithBody(ctx context.Context, clientId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutClientClientIdCapabilities(ctx context.Context, clientId string, body PutClientClientIdCapabilitiesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostClientClientIdDeploymentDeploymentIdStatusWithBody request with any body
	PostClientClientIdDeploymentDeploymentIdStatusWithBody(ctx context.Context, clientId string, deploymentId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostClientClientIdDeploymentDeploymentIdStatus(ctx context.Context, clientId string, deploymentId openapi_types.UUID, body PostClientClientIdDeploymentDeploymentIdStatusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StateWithBody request with any body
	StateWithBody(ctx context.Context, clientId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	State(ctx context.Context, clientId string, body StateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostOnboardingWithBody request with any body
	PostOnboardingWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostOnboarding(ctx context.Context, body PostOnboardingJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetOnboardingRootCA request
	GetOnboardingRootCA(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ProcessWithBody request with any body
	ProcessWithBody(ctx context.Context, params *ProcessParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	Process(ctx context.Context, params *ProcessParams, body ProcessJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostClientClientIdCapabilitiesWithBody(ctx context.Context, clientId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostClientClientIdCapabilitiesRequestWithBody(c.Server, clientId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostClientClientIdCapabilities(ctx context.Context, clientId string, body PostClientClientIdCapabilitiesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostClientClientIdCapabilitiesRequest(c.Server, clientId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutClientClientIdCapabilitiesWithBody(ctx context.Context, clientId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutClientClientIdCapabilitiesRequestWithBody(c.Server, clientId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutClientClientIdCapabilities(ctx context.Context, clientId string, body PutClientClientIdCapabilitiesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutClientClientIdCapabilitiesRequest(c.Server, clientId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostClientClientIdDeploymentDeploymentIdStatusWithBody(ctx context.Context, clientId string, deploymentId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostClientClientIdDeploymentDeploymentIdStatusRequestWithBody(c.Server, clientId, deploymentId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostClientClientIdDeploymentDeploymentIdStatus(ctx context.Context, clientId string, deploymentId openapi_types.UUID, body PostClientClientIdDeploymentDeploymentIdStatusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostClientClientIdDeploymentDeploymentIdStatusRequest(c.Server, clientId, deploymentId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StateWithBody(ctx context.Context, clientId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStateRequestWithBody(c.Server, clientId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) State(ctx context.Context, clientId string, body StateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStateRequest(c.Server, clientId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostOnboardingWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostOnboardingRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostOnboarding(ctx context.Context, body PostOnboardingJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostOnboardingRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetOnboardingRootCA(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetOnboardingRootCARequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ProcessWithBody(ctx context.Context, params *ProcessParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewProcessRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Process(ctx context.Context, params *ProcessParams, body ProcessJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewProcessRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostClientClientIdCapabilitiesRequest calls the generic PostClientClientIdCapabilities builder with application/json body
func NewPostClientClientIdCapabilitiesRequest(server string, clientId string, body PostClientClientIdCapabilitiesJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostClientClientIdCapabilitiesRequestWithBody(server, clientId, "application/json", bodyReader)
}

// NewPostClientClientIdCapabilitiesRequestWithBody generates requests for PostClientClientIdCapabilities with any type of body
func NewPostClientClientIdCapabilitiesRequestWithBody(server string, clientId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "clientId", runtime.ParamLocationPath, clientId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/client/%s/capabilities", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPutClientClientIdCapabilitiesRequest calls the generic PutClientClientIdCapabilities builder with application/json body
func NewPutClientClientIdCapabilitiesRequest(server string, clientId string, body PutClientClientIdCapabilitiesJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutClientClientIdCapabilitiesRequestWithBody(server, clientId, "application/json", bodyReader)
}

// NewPutClientClientIdCapabilitiesRequestWithBody generates requests for PutClientClientIdCapabilities with any type of body
func NewPutClientClientIdCapabilitiesRequestWithBody(server string, clientId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "clientId", runtime.ParamLocationPath, clientId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/client/%s/capabilities", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostClientClientIdDeploymentDeploymentIdStatusRequest calls the generic PostClientClientIdDeploymentDeploymentIdStatus builder with application/json body
func NewPostClientClientIdDeploymentDeploymentIdStatusRequest(server string, clientId string, deploymentId openapi_types.UUID, body PostClientClientIdDeploymentDeploymentIdStatusJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostClientClientIdDeploymentDeploymentIdStatusRequestWithBody(server, clientId, deploymentId, "application/json", bodyReader)
}

// NewPostClientClientIdDeploymentDeploymentIdStatusRequestWithBody generates requests for PostClientClientIdDeploymentDeploymentIdStatus with any type of body
func NewPostClientClientIdDeploymentDeploymentIdStatusRequestWithBody(server string, clientId string, deploymentId openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "clientId", runtime.ParamLocationPath, clientId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "deploymentId", runtime.ParamLocationPath, deploymentId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/client/%s/deployment/%s/status", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewStateRequest calls the generic State builder with application/json body
func NewStateRequest(server string, clientId string, body StateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewStateRequestWithBody(server, clientId, "application/json", bodyReader)
}

// NewStateRequestWithBody generates requests for State with any type of body
func NewStateRequestWithBody(server string, clientId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "clientId", runtime.ParamLocationPath, clientId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/client/%s/wfm/state", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostOnboardingRequest calls the generic PostOnboarding builder with application/json body
func NewPostOnboardingRequest(server string, body PostOnboardingJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostOnboardingRequestWithBody(server, "application/json", bodyReader)
}

// NewPostOnboardingRequestWithBody generates requests for PostOnboarding with any type of body
func NewPostOnboardingRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/onboarding")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetOnboardingRootCARequest generates requests for GetOnboardingRootCA
func NewGetOnboardingRootCARequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/onboarding/rootCA")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewProcessRequest calls the generic Process builder with application/json body
func NewProcessRequest(server string, params *ProcessParams, body ProcessJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewProcessRequestWithBody(server, params, "application/json", bodyReader)
}

// NewProcessRequestWithBody generates requests for Process with any type of body
func NewProcessRequestWithBody(server string, params *ProcessParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/wfm/process")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.RpcId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "rpcId", runtime.ParamLocationQuery, *params.RpcId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostClientClientIdCapabilitiesWithBodyWithResponse request with any body
	PostClientClientIdCapabilitiesWithBodyWithResponse(ctx context.Context, clientId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostClientClientIdCapabilitiesResponse, error)

	PostClientClientIdCapabilitiesWithResponse(ctx context.Context, clientId string, body PostClientClientIdCapabilitiesJSONRequestBody, reqEditors ...RequestEditorFn) (*PostClientClientIdCapabilitiesResponse, error)

	// PutClientClientIdCapabilitiesWithBodyWithResponse request with any body
	PutClientClientIdCapabilitiesWithBodyWithResponse(ctx context.Context, clientId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutClientClientIdCapabilitiesResponse, error)

	PutClientClientIdCapabilitiesWithResponse(ctx context.Context, clientId string, body PutClientClientIdCapabilitiesJSONRequestBody, reqEditors ...RequestEditorFn) (*PutClientClientIdCapabilitiesResponse, error)

	// PostClientClientIdDeploymentDeploymentIdStatusWithBodyWithResponse request with any body
	PostClientClientIdDeploymentDeploymentIdStatusWithBodyWithResponse(ctx context.Context, clientId string, deploymentId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostClientClientIdDeploymentDeploymentIdStatusResponse, error)

	PostClientClientIdDeploymentDeploymentIdStatusWithResponse(ctx context.Context, clientId string, deploymentId openapi_types.UUID, body PostClientClientIdDeploymentDeploymentIdStatusJSONRequestBody, reqEditors ...RequestEditorFn) (*PostClientClientIdDeploymentDeploymentIdStatusResponse, error)

	// StateWithBodyWithResponse request with any body
	StateWithBodyWithResponse(ctx context.Context, clientId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*StateResponse, error)

	StateWithResponse(ctx context.Context, clientId string, body StateJSONRequestBody, reqEditors ...RequestEditorFn) (*StateResponse, error)

	// PostOnboardingWithBodyWithResponse request with any body
	PostOnboardingWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostOnboardingResponse, error)

	PostOnboardingWithResponse(ctx context.Context, body PostOnboardingJSONRequestBody, reqEditors ...RequestEditorFn) (*PostOnboardingResponse, error)

	// GetOnboardingRootCAWithResponse request
	GetOnboardingRootCAWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetOnboardingRootCAResponse, error)

	// ProcessWithBodyWithResponse request with any body
	ProcessWithBodyWithResponse(ctx context.Context, params *ProcessParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ProcessResponse, error)

	ProcessWithResponse(ctx context.Context, params *ProcessParams, body ProcessJSONRequestBody, reqEditors ...RequestEditorFn) (*ProcessResponse, error)
}

type PostClientClientIdCapabilitiesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r PostClientClientIdCapabilitiesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostClientClientIdCapabilitiesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutClientClientIdCapabilitiesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r PutClientClientIdCapabilitiesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutClientClientIdCapabilitiesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostClientClientIdDeploymentDeploymentIdStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r PostClientClientIdDeploymentDeploymentIdStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostClientClientIdDeploymentDeploymentIdStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type StateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DesiredAppStates
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r StateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostOnboardingResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *OnboardingResponse
	JSON400      *Error
	JSON409      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r PostOnboardingResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostOnboardingResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetOnboardingRootCAResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Certificate Base64-encoded certificate
		Certificate *string `json:"certificate,omitempty"`
	}
	JSON500 *Error
}

// Status returns HTTPResponse.Status
func (r GetOnboardingRootCAResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetOnboardingRootCAResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ProcessResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PrivatePayload
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r ProcessResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ProcessResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostClientClientIdCapabilitiesWithBodyWithResponse request with arbitrary body returning *PostClientClientIdCapabilitiesResponse
func (c *ClientWithResponses) PostClientClientIdCapabilitiesWithBodyWithResponse(ctx context.Context, clientId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostClientClientIdCapabilitiesResponse, error) {
	rsp, err := c.PostClientClientIdCapabilitiesWithBody(ctx, clientId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostClientClientIdCapabilitiesResponse(rsp)
}

func (c *ClientWithResponses) PostClientClientIdCapabilitiesWithResponse(ctx context.Context, clientId string, body PostClientClientIdCapabilitiesJSONRequestBody, reqEditors ...RequestEditorFn) (*PostClientClientIdCapabilitiesResponse, error) {
	rsp, err := c.PostClientClientIdCapabilities(ctx, clientId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostClientClientIdCapabilitiesResponse(rsp)
}

// PutClientClientIdCapabilitiesWithBodyWithResponse request with arbitrary body returning *PutClientClientIdCapabilitiesResponse
func (c *ClientWithResponses) PutClientClientIdCapabilitiesWithBodyWithResponse(ctx context.Context, clientId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutClientClientIdCapabilitiesResponse, error) {
	rsp, err := c.PutClientClientIdCapabilitiesWithBody(ctx, clientId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutClientClientIdCapabilitiesResponse(rsp)
}

func (c *ClientWithResponses) PutClientClientIdCapabilitiesWithResponse(ctx context.Context, clientId string, body PutClientClientIdCapabilitiesJSONRequestBody, reqEditors ...RequestEditorFn) (*PutClientClientIdCapabilitiesResponse, error) {
	rsp, err := c.PutClientClientIdCapabilities(ctx, clientId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutClientClientIdCapabilitiesResponse(rsp)
}

// PostClientClientIdDeploymentDeploymentIdStatusWithBodyWithResponse request with arbitrary body returning *PostClientClientIdDeploymentDeploymentIdStatusResponse
func (c *ClientWithResponses) PostClientClientIdDeploymentDeploymentIdStatusWithBodyWithResponse(ctx context.Context, clientId string, deploymentId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostClientClientIdDeploymentDeploymentIdStatusResponse, error) {
	rsp, err := c.PostClientClientIdDeploymentDeploymentIdStatusWithBody(ctx, clientId, deploymentId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostClientClientIdDeploymentDeploymentIdStatusResponse(rsp)
}

func (c *ClientWithResponses) PostClientClientIdDeploymentDeploymentIdStatusWithResponse(ctx context.Context, clientId string, deploymentId openapi_types.UUID, body PostClientClientIdDeploymentDeploymentIdStatusJSONRequestBody, reqEditors ...RequestEditorFn) (*PostClientClientIdDeploymentDeploymentIdStatusResponse, error) {
	rsp, err := c.PostClientClientIdDeploymentDeploymentIdStatus(ctx, clientId, deploymentId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostClientClientIdDeploymentDeploymentIdStatusResponse(rsp)
}

// StateWithBodyWithResponse request with arbitrary body returning *StateResponse
func (c *ClientWithResponses) StateWithBodyWithResponse(ctx context.Context, clientId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*StateResponse, error) {
	rsp, err := c.StateWithBody(ctx, clientId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStateResponse(rsp)
}

func (c *ClientWithResponses) StateWithResponse(ctx context.Context, clientId string, body StateJSONRequestBody, reqEditors ...RequestEditorFn) (*StateResponse, error) {
	rsp, err := c.State(ctx, clientId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStateResponse(rsp)
}

// PostOnboardingWithBodyWithResponse request with arbitrary body returning *PostOnboardingResponse
func (c *ClientWithResponses) PostOnboardingWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostOnboardingResponse, error) {
	rsp, err := c.PostOnboardingWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostOnboardingResponse(rsp)
}

func (c *ClientWithResponses) PostOnboardingWithResponse(ctx context.Context, body PostOnboardingJSONRequestBody, reqEditors ...RequestEditorFn) (*PostOnboardingResponse, error) {
	rsp, err := c.PostOnboarding(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostOnboardingResponse(rsp)
}

// GetOnboardingRootCAWithResponse request returning *GetOnboardingRootCAResponse
func (c *ClientWithResponses) GetOnboardingRootCAWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetOnboardingRootCAResponse, error) {
	rsp, err := c.GetOnboardingRootCA(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetOnboardingRootCAResponse(rsp)
}

// ProcessWithBodyWithResponse request with arbitrary body returning *ProcessResponse
func (c *ClientWithResponses) ProcessWithBodyWithResponse(ctx context.Context, params *ProcessParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ProcessResponse, error) {
	rsp, err := c.ProcessWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseProcessResponse(rsp)
}

func (c *ClientWithResponses) ProcessWithResponse(ctx context.Context, params *ProcessParams, body ProcessJSONRequestBody, reqEditors ...RequestEditorFn) (*ProcessResponse, error) {
	rsp, err := c.Process(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseProcessResponse(rsp)
}

// ParsePostClientClientIdCapabilitiesResponse parses an HTTP response from a PostClientClientIdCapabilitiesWithResponse call
func ParsePostClientClientIdCapabilitiesResponse(rsp *http.Response) (*PostClientClientIdCapabilitiesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostClientClientIdCapabilitiesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePutClientClientIdCapabilitiesResponse parses an HTTP response from a PutClientClientIdCapabilitiesWithResponse call
func ParsePutClientClientIdCapabilitiesResponse(rsp *http.Response) (*PutClientClientIdCapabilitiesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutClientClientIdCapabilitiesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostClientClientIdDeploymentDeploymentIdStatusResponse parses an HTTP response from a PostClientClientIdDeploymentDeploymentIdStatusWithResponse call
func ParsePostClientClientIdDeploymentDeploymentIdStatusResponse(rsp *http.Response) (*PostClientClientIdDeploymentDeploymentIdStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostClientClientIdDeploymentDeploymentIdStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseStateResponse parses an HTTP response from a StateWithResponse call
func ParseStateResponse(rsp *http.Response) (*StateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DesiredAppStates
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParsePostOnboardingResponse parses an HTTP response from a PostOnboardingWithResponse call
func ParsePostOnboardingResponse(rsp *http.Response) (*PostOnboardingResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostOnboardingResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest OnboardingResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetOnboardingRootCAResponse parses an HTTP response from a GetOnboardingRootCAWithResponse call
func ParseGetOnboardingRootCAResponse(rsp *http.Response) (*GetOnboardingRootCAResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetOnboardingRootCAResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Certificate Base64-encoded certificate
			Certificate *string `json:"certificate,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseProcessResponse parses an HTTP response from a ProcessWithResponse call
func ParseProcessResponse(rsp *http.Response) (*ProcessResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ProcessResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PrivatePayload
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
