// Package sbi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package sbi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostDeviceDeviceIdCapabilitiesWithBody request with any body
	PostDeviceDeviceIdCapabilitiesWithBody(ctx context.Context, deviceId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostDeviceDeviceIdCapabilities(ctx context.Context, deviceId string, body PostDeviceDeviceIdCapabilitiesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutDeviceDeviceIdCapabilitiesWithBody request with any body
	PutDeviceDeviceIdCapabilitiesWithBody(ctx context.Context, deviceId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutDeviceDeviceIdCapabilities(ctx context.Context, deviceId string, body PutDeviceDeviceIdCapabilitiesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostDeviceDeviceIdDeploymentDeploymentIdStatusWithBody request with any body
	PostDeviceDeviceIdDeploymentDeploymentIdStatusWithBody(ctx context.Context, deviceId string, deploymentId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostDeviceDeviceIdDeploymentDeploymentIdStatus(ctx context.Context, deviceId string, deploymentId openapi_types.UUID, body PostDeviceDeviceIdDeploymentDeploymentIdStatusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostOnboardingDeviceWithBody request with any body
	PostOnboardingDeviceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostOnboardingDevice(ctx context.Context, body PostOnboardingDeviceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetOnboardingRootCA request
	GetOnboardingRootCA(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ProcessWithBody request with any body
	ProcessWithBody(ctx context.Context, params *ProcessParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	Process(ctx context.Context, params *ProcessParams, body ProcessJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StateWithBody request with any body
	StateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	State(ctx context.Context, body StateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostDeviceDeviceIdCapabilitiesWithBody(ctx context.Context, deviceId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostDeviceDeviceIdCapabilitiesRequestWithBody(c.Server, deviceId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostDeviceDeviceIdCapabilities(ctx context.Context, deviceId string, body PostDeviceDeviceIdCapabilitiesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostDeviceDeviceIdCapabilitiesRequest(c.Server, deviceId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutDeviceDeviceIdCapabilitiesWithBody(ctx context.Context, deviceId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutDeviceDeviceIdCapabilitiesRequestWithBody(c.Server, deviceId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutDeviceDeviceIdCapabilities(ctx context.Context, deviceId string, body PutDeviceDeviceIdCapabilitiesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutDeviceDeviceIdCapabilitiesRequest(c.Server, deviceId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostDeviceDeviceIdDeploymentDeploymentIdStatusWithBody(ctx context.Context, deviceId string, deploymentId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostDeviceDeviceIdDeploymentDeploymentIdStatusRequestWithBody(c.Server, deviceId, deploymentId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostDeviceDeviceIdDeploymentDeploymentIdStatus(ctx context.Context, deviceId string, deploymentId openapi_types.UUID, body PostDeviceDeviceIdDeploymentDeploymentIdStatusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostDeviceDeviceIdDeploymentDeploymentIdStatusRequest(c.Server, deviceId, deploymentId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostOnboardingDeviceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostOnboardingDeviceRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostOnboardingDevice(ctx context.Context, body PostOnboardingDeviceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostOnboardingDeviceRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetOnboardingRootCA(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetOnboardingRootCARequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ProcessWithBody(ctx context.Context, params *ProcessParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewProcessRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Process(ctx context.Context, params *ProcessParams, body ProcessJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewProcessRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStateRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) State(ctx context.Context, body StateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStateRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostDeviceDeviceIdCapabilitiesRequest calls the generic PostDeviceDeviceIdCapabilities builder with application/json body
func NewPostDeviceDeviceIdCapabilitiesRequest(server string, deviceId string, body PostDeviceDeviceIdCapabilitiesJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostDeviceDeviceIdCapabilitiesRequestWithBody(server, deviceId, "application/json", bodyReader)
}

// NewPostDeviceDeviceIdCapabilitiesRequestWithBody generates requests for PostDeviceDeviceIdCapabilities with any type of body
func NewPostDeviceDeviceIdCapabilitiesRequestWithBody(server string, deviceId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "deviceId", runtime.ParamLocationPath, deviceId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/device/%s/capabilities", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPutDeviceDeviceIdCapabilitiesRequest calls the generic PutDeviceDeviceIdCapabilities builder with application/json body
func NewPutDeviceDeviceIdCapabilitiesRequest(server string, deviceId string, body PutDeviceDeviceIdCapabilitiesJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutDeviceDeviceIdCapabilitiesRequestWithBody(server, deviceId, "application/json", bodyReader)
}

// NewPutDeviceDeviceIdCapabilitiesRequestWithBody generates requests for PutDeviceDeviceIdCapabilities with any type of body
func NewPutDeviceDeviceIdCapabilitiesRequestWithBody(server string, deviceId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "deviceId", runtime.ParamLocationPath, deviceId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/device/%s/capabilities", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostDeviceDeviceIdDeploymentDeploymentIdStatusRequest calls the generic PostDeviceDeviceIdDeploymentDeploymentIdStatus builder with application/json body
func NewPostDeviceDeviceIdDeploymentDeploymentIdStatusRequest(server string, deviceId string, deploymentId openapi_types.UUID, body PostDeviceDeviceIdDeploymentDeploymentIdStatusJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostDeviceDeviceIdDeploymentDeploymentIdStatusRequestWithBody(server, deviceId, deploymentId, "application/json", bodyReader)
}

// NewPostDeviceDeviceIdDeploymentDeploymentIdStatusRequestWithBody generates requests for PostDeviceDeviceIdDeploymentDeploymentIdStatus with any type of body
func NewPostDeviceDeviceIdDeploymentDeploymentIdStatusRequestWithBody(server string, deviceId string, deploymentId openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "deviceId", runtime.ParamLocationPath, deviceId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "deploymentId", runtime.ParamLocationPath, deploymentId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/device/%s/deployment/%s/status", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostOnboardingDeviceRequest calls the generic PostOnboardingDevice builder with application/json body
func NewPostOnboardingDeviceRequest(server string, body PostOnboardingDeviceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostOnboardingDeviceRequestWithBody(server, "application/json", bodyReader)
}

// NewPostOnboardingDeviceRequestWithBody generates requests for PostOnboardingDevice with any type of body
func NewPostOnboardingDeviceRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/onboarding/device")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetOnboardingRootCARequest generates requests for GetOnboardingRootCA
func NewGetOnboardingRootCARequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/onboarding/rootCA")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewProcessRequest calls the generic Process builder with application/json body
func NewProcessRequest(server string, params *ProcessParams, body ProcessJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewProcessRequestWithBody(server, params, "application/json", bodyReader)
}

// NewProcessRequestWithBody generates requests for Process with any type of body
func NewProcessRequestWithBody(server string, params *ProcessParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/wfm/process")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.RpcId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "rpcId", runtime.ParamLocationQuery, *params.RpcId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewStateRequest calls the generic State builder with application/json body
func NewStateRequest(server string, body StateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewStateRequestWithBody(server, "application/json", bodyReader)
}

// NewStateRequestWithBody generates requests for State with any type of body
func NewStateRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/wfm/state")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostDeviceDeviceIdCapabilitiesWithBodyWithResponse request with any body
	PostDeviceDeviceIdCapabilitiesWithBodyWithResponse(ctx context.Context, deviceId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostDeviceDeviceIdCapabilitiesResponse, error)

	PostDeviceDeviceIdCapabilitiesWithResponse(ctx context.Context, deviceId string, body PostDeviceDeviceIdCapabilitiesJSONRequestBody, reqEditors ...RequestEditorFn) (*PostDeviceDeviceIdCapabilitiesResponse, error)

	// PutDeviceDeviceIdCapabilitiesWithBodyWithResponse request with any body
	PutDeviceDeviceIdCapabilitiesWithBodyWithResponse(ctx context.Context, deviceId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutDeviceDeviceIdCapabilitiesResponse, error)

	PutDeviceDeviceIdCapabilitiesWithResponse(ctx context.Context, deviceId string, body PutDeviceDeviceIdCapabilitiesJSONRequestBody, reqEditors ...RequestEditorFn) (*PutDeviceDeviceIdCapabilitiesResponse, error)

	// PostDeviceDeviceIdDeploymentDeploymentIdStatusWithBodyWithResponse request with any body
	PostDeviceDeviceIdDeploymentDeploymentIdStatusWithBodyWithResponse(ctx context.Context, deviceId string, deploymentId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostDeviceDeviceIdDeploymentDeploymentIdStatusResponse, error)

	PostDeviceDeviceIdDeploymentDeploymentIdStatusWithResponse(ctx context.Context, deviceId string, deploymentId openapi_types.UUID, body PostDeviceDeviceIdDeploymentDeploymentIdStatusJSONRequestBody, reqEditors ...RequestEditorFn) (*PostDeviceDeviceIdDeploymentDeploymentIdStatusResponse, error)

	// PostOnboardingDeviceWithBodyWithResponse request with any body
	PostOnboardingDeviceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostOnboardingDeviceResponse, error)

	PostOnboardingDeviceWithResponse(ctx context.Context, body PostOnboardingDeviceJSONRequestBody, reqEditors ...RequestEditorFn) (*PostOnboardingDeviceResponse, error)

	// GetOnboardingRootCAWithResponse request
	GetOnboardingRootCAWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetOnboardingRootCAResponse, error)

	// ProcessWithBodyWithResponse request with any body
	ProcessWithBodyWithResponse(ctx context.Context, params *ProcessParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ProcessResponse, error)

	ProcessWithResponse(ctx context.Context, params *ProcessParams, body ProcessJSONRequestBody, reqEditors ...RequestEditorFn) (*ProcessResponse, error)

	// StateWithBodyWithResponse request with any body
	StateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*StateResponse, error)

	StateWithResponse(ctx context.Context, body StateJSONRequestBody, reqEditors ...RequestEditorFn) (*StateResponse, error)
}

type PostDeviceDeviceIdCapabilitiesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r PostDeviceDeviceIdCapabilitiesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostDeviceDeviceIdCapabilitiesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutDeviceDeviceIdCapabilitiesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r PutDeviceDeviceIdCapabilitiesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutDeviceDeviceIdCapabilitiesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostDeviceDeviceIdDeploymentDeploymentIdStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r PostDeviceDeviceIdDeploymentDeploymentIdStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostDeviceDeviceIdDeploymentDeploymentIdStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostOnboardingDeviceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *OnboardingResponse
	JSON400      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r PostOnboardingDeviceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostOnboardingDeviceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetOnboardingRootCAResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GetOnboardingRootCAResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetOnboardingRootCAResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ProcessResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PrivatePayload
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r ProcessResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ProcessResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type StateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DesiredAppStates
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r StateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostDeviceDeviceIdCapabilitiesWithBodyWithResponse request with arbitrary body returning *PostDeviceDeviceIdCapabilitiesResponse
func (c *ClientWithResponses) PostDeviceDeviceIdCapabilitiesWithBodyWithResponse(ctx context.Context, deviceId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostDeviceDeviceIdCapabilitiesResponse, error) {
	rsp, err := c.PostDeviceDeviceIdCapabilitiesWithBody(ctx, deviceId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostDeviceDeviceIdCapabilitiesResponse(rsp)
}

func (c *ClientWithResponses) PostDeviceDeviceIdCapabilitiesWithResponse(ctx context.Context, deviceId string, body PostDeviceDeviceIdCapabilitiesJSONRequestBody, reqEditors ...RequestEditorFn) (*PostDeviceDeviceIdCapabilitiesResponse, error) {
	rsp, err := c.PostDeviceDeviceIdCapabilities(ctx, deviceId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostDeviceDeviceIdCapabilitiesResponse(rsp)
}

// PutDeviceDeviceIdCapabilitiesWithBodyWithResponse request with arbitrary body returning *PutDeviceDeviceIdCapabilitiesResponse
func (c *ClientWithResponses) PutDeviceDeviceIdCapabilitiesWithBodyWithResponse(ctx context.Context, deviceId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutDeviceDeviceIdCapabilitiesResponse, error) {
	rsp, err := c.PutDeviceDeviceIdCapabilitiesWithBody(ctx, deviceId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutDeviceDeviceIdCapabilitiesResponse(rsp)
}

func (c *ClientWithResponses) PutDeviceDeviceIdCapabilitiesWithResponse(ctx context.Context, deviceId string, body PutDeviceDeviceIdCapabilitiesJSONRequestBody, reqEditors ...RequestEditorFn) (*PutDeviceDeviceIdCapabilitiesResponse, error) {
	rsp, err := c.PutDeviceDeviceIdCapabilities(ctx, deviceId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutDeviceDeviceIdCapabilitiesResponse(rsp)
}

// PostDeviceDeviceIdDeploymentDeploymentIdStatusWithBodyWithResponse request with arbitrary body returning *PostDeviceDeviceIdDeploymentDeploymentIdStatusResponse
func (c *ClientWithResponses) PostDeviceDeviceIdDeploymentDeploymentIdStatusWithBodyWithResponse(ctx context.Context, deviceId string, deploymentId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostDeviceDeviceIdDeploymentDeploymentIdStatusResponse, error) {
	rsp, err := c.PostDeviceDeviceIdDeploymentDeploymentIdStatusWithBody(ctx, deviceId, deploymentId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostDeviceDeviceIdDeploymentDeploymentIdStatusResponse(rsp)
}

func (c *ClientWithResponses) PostDeviceDeviceIdDeploymentDeploymentIdStatusWithResponse(ctx context.Context, deviceId string, deploymentId openapi_types.UUID, body PostDeviceDeviceIdDeploymentDeploymentIdStatusJSONRequestBody, reqEditors ...RequestEditorFn) (*PostDeviceDeviceIdDeploymentDeploymentIdStatusResponse, error) {
	rsp, err := c.PostDeviceDeviceIdDeploymentDeploymentIdStatus(ctx, deviceId, deploymentId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostDeviceDeviceIdDeploymentDeploymentIdStatusResponse(rsp)
}

// PostOnboardingDeviceWithBodyWithResponse request with arbitrary body returning *PostOnboardingDeviceResponse
func (c *ClientWithResponses) PostOnboardingDeviceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostOnboardingDeviceResponse, error) {
	rsp, err := c.PostOnboardingDeviceWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostOnboardingDeviceResponse(rsp)
}

func (c *ClientWithResponses) PostOnboardingDeviceWithResponse(ctx context.Context, body PostOnboardingDeviceJSONRequestBody, reqEditors ...RequestEditorFn) (*PostOnboardingDeviceResponse, error) {
	rsp, err := c.PostOnboardingDevice(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostOnboardingDeviceResponse(rsp)
}

// GetOnboardingRootCAWithResponse request returning *GetOnboardingRootCAResponse
func (c *ClientWithResponses) GetOnboardingRootCAWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetOnboardingRootCAResponse, error) {
	rsp, err := c.GetOnboardingRootCA(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetOnboardingRootCAResponse(rsp)
}

// ProcessWithBodyWithResponse request with arbitrary body returning *ProcessResponse
func (c *ClientWithResponses) ProcessWithBodyWithResponse(ctx context.Context, params *ProcessParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ProcessResponse, error) {
	rsp, err := c.ProcessWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseProcessResponse(rsp)
}

func (c *ClientWithResponses) ProcessWithResponse(ctx context.Context, params *ProcessParams, body ProcessJSONRequestBody, reqEditors ...RequestEditorFn) (*ProcessResponse, error) {
	rsp, err := c.Process(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseProcessResponse(rsp)
}

// StateWithBodyWithResponse request with arbitrary body returning *StateResponse
func (c *ClientWithResponses) StateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*StateResponse, error) {
	rsp, err := c.StateWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStateResponse(rsp)
}

func (c *ClientWithResponses) StateWithResponse(ctx context.Context, body StateJSONRequestBody, reqEditors ...RequestEditorFn) (*StateResponse, error) {
	rsp, err := c.State(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStateResponse(rsp)
}

// ParsePostDeviceDeviceIdCapabilitiesResponse parses an HTTP response from a PostDeviceDeviceIdCapabilitiesWithResponse call
func ParsePostDeviceDeviceIdCapabilitiesResponse(rsp *http.Response) (*PostDeviceDeviceIdCapabilitiesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostDeviceDeviceIdCapabilitiesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePutDeviceDeviceIdCapabilitiesResponse parses an HTTP response from a PutDeviceDeviceIdCapabilitiesWithResponse call
func ParsePutDeviceDeviceIdCapabilitiesResponse(rsp *http.Response) (*PutDeviceDeviceIdCapabilitiesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutDeviceDeviceIdCapabilitiesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostDeviceDeviceIdDeploymentDeploymentIdStatusResponse parses an HTTP response from a PostDeviceDeviceIdDeploymentDeploymentIdStatusWithResponse call
func ParsePostDeviceDeviceIdDeploymentDeploymentIdStatusResponse(rsp *http.Response) (*PostDeviceDeviceIdDeploymentDeploymentIdStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostDeviceDeviceIdDeploymentDeploymentIdStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostOnboardingDeviceResponse parses an HTTP response from a PostOnboardingDeviceWithResponse call
func ParsePostOnboardingDeviceResponse(rsp *http.Response) (*PostOnboardingDeviceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostOnboardingDeviceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest OnboardingResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetOnboardingRootCAResponse parses an HTTP response from a GetOnboardingRootCAWithResponse call
func ParseGetOnboardingRootCAResponse(rsp *http.Response) (*GetOnboardingRootCAResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetOnboardingRootCAResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseProcessResponse parses an HTTP response from a ProcessWithResponse call
func ParseProcessResponse(rsp *http.Response) (*ProcessResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ProcessResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PrivatePayload
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseStateResponse parses an HTTP response from a StateWithResponse call
func ParseStateResponse(rsp *http.Response) (*StateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DesiredAppStates
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
