// Package sbi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package sbi

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

const (
	Margo_authScopes = "margo_auth.Scopes"
)

// Defines values for AppDeploymentProfileType.
const (
	Compose AppDeploymentProfileType = "compose"
	HelmV3  AppDeploymentProfileType = "helm.v3"
)

// Defines values for AppStateAppState.
const (
	CRASHLOOP AppStateAppState = "CRASHLOOP"
	REMOVE    AppStateAppState = "REMOVE"
	RUNNING   AppStateAppState = "RUNNING"
	STOPPED   AppStateAppState = "STOPPED"
	UPDATING  AppStateAppState = "UPDATING"
)

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// AppDeployment Application Deployment manifest
type AppDeployment struct {
	// ApiVersion API version
	ApiVersion string `json:"apiVersion"`

	// Kind Resource kind
	Kind     string                `json:"kind"`
	Metadata AppDeploymentMetadata `json:"metadata"`

	// Spec Application Deployment specification
	Spec AppDeploymentSpec `json:"spec"`
}

// AppDeploymentMetadata defines model for appDeploymentMetadata.
type AppDeploymentMetadata struct {
	// Annotations Annotations for the resource
	Annotations *map[string]string `json:"annotations,omitempty"`

	// Id Unique identifier for the application deployment
	Id *string `json:"id,omitempty"`

	// Labels Labels for the resource
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Name of the resource
	Name string `json:"name"`

	// Namespace Namespace of the resource
	Namespace *string `json:"namespace,omitempty"`
}

// AppDeploymentParams Application Parameters
type AppDeploymentParams map[string]AppParameterValue

// AppDeploymentProfile Application Deployment Profile
type AppDeploymentProfile struct {
	// Components Components of the deployment profile
	Components []AppDeploymentProfile_Components_Item `json:"components"`

	// Type Type of deployment profile
	Type AppDeploymentProfileType `json:"type"`
}

// AppDeploymentProfile_Components_Item defines model for appDeploymentProfile.components.Item.
type AppDeploymentProfile_Components_Item struct {
	union json.RawMessage
}

// AppDeploymentProfileType Type of deployment profile
type AppDeploymentProfileType string

// AppDeploymentSpec Application Deployment specification
type AppDeploymentSpec struct {
	// DeploymentProfile Application Deployment Profile
	DeploymentProfile AppDeploymentProfile `json:"deploymentProfile"`

	// Parameters Application Parameters
	Parameters *AppDeploymentParams `json:"parameters,omitempty"`
}

// AppParameterTarget Application Parameter Target
type AppParameterTarget struct {
	// Components Components of the parameter
	Components []string `json:"components"`

	// Pointer Pointer to the parameter
	Pointer string `json:"pointer"`
}

// AppParameterValue Application Parameter Value
type AppParameterValue struct {
	// Targets Targets of the parameter
	Targets []AppParameterTarget `json:"targets"`

	// Value Value of the parameter
	Value string `json:"value"`
}

// AppState defines model for appState.
type AppState struct {
	// AppDeploymentYAML Base64 encoded MARGO ApplicationDescription YAML content
	AppDeploymentYAML *string `json:"appDeploymentYAML,omitempty"`

	// AppDeploymentYAMLHash App Hash encoding used for versioning the MARGO ApplicationDescription
	AppDeploymentYAMLHash string           `json:"appDeploymentYAMLHash"`
	AppId                 string           `json:"appId"`
	AppState              AppStateAppState `json:"appState"`

	// AppVersion Version String
	AppVersion string `json:"appVersion"`
}

// AppStateAppState defines model for AppState.AppState.
type AppStateAppState string

// ComposeApplicationDeploymentProfileComponent Compose Application Deployment Profile Component
type ComposeApplicationDeploymentProfileComponent struct {
	// Name Name of the component
	Name       string `json:"name"`
	Properties struct {
		// KeyLocation Key location of the component
		KeyLocation *string `json:"keyLocation,omitempty"`

		// PackageLocation Package location of the component
		PackageLocation string `json:"packageLocation"`

		// Timeout Timeout for the component
		Timeout *string `json:"timeout,omitempty"`

		// Wait Wait for the component to be ready
		Wait *bool `json:"wait,omitempty"`
	} `json:"properties"`
}

// CurrentAppStates defines model for currentAppStates.
type CurrentAppStates = []AppState

// DesiredAppStates defines model for desiredAppStates.
type DesiredAppStates = []AppState

// HelmApplicationDeploymentProfileComponent Helm Application Deployment Profile Component
type HelmApplicationDeploymentProfileComponent struct {
	// Name Name of the component
	Name       string `json:"name"`
	Properties struct {
		// Repository Repository of the component
		Repository string `json:"repository"`

		// Revision Revision of the component
		Revision *string `json:"revision,omitempty"`

		// Timeout Timeout for the component
		Timeout *string `json:"timeout,omitempty"`

		// Wait Wait for the component to be ready
		Wait *bool `json:"wait,omitempty"`
	} `json:"properties"`
}

// PrivatePayload defines model for privatePayload.
type PrivatePayload struct {
	Code *string `json:"code,omitempty"`
}

// UserArray defines model for UserArray.
type UserArray = []string

// ProcessParams defines parameters for Process.
type ProcessParams struct {
	// RpcId An RPC call to the WFM, initiated by the Device
	RpcId *int `form:"rpcId,omitempty" json:"rpcId,omitempty"`
}

// ProcessJSONRequestBody defines body for Process for application/json ContentType.
type ProcessJSONRequestBody = PrivatePayload

// StateJSONRequestBody defines body for State for application/json ContentType.
type StateJSONRequestBody = CurrentAppStates

// AsHelmApplicationDeploymentProfileComponent returns the union data inside the AppDeploymentProfile_Components_Item as a HelmApplicationDeploymentProfileComponent
func (t AppDeploymentProfile_Components_Item) AsHelmApplicationDeploymentProfileComponent() (HelmApplicationDeploymentProfileComponent, error) {
	var body HelmApplicationDeploymentProfileComponent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromHelmApplicationDeploymentProfileComponent overwrites any union data inside the AppDeploymentProfile_Components_Item as the provided HelmApplicationDeploymentProfileComponent
func (t *AppDeploymentProfile_Components_Item) FromHelmApplicationDeploymentProfileComponent(v HelmApplicationDeploymentProfileComponent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeHelmApplicationDeploymentProfileComponent performs a merge with any union data inside the AppDeploymentProfile_Components_Item, using the provided HelmApplicationDeploymentProfileComponent
func (t *AppDeploymentProfile_Components_Item) MergeHelmApplicationDeploymentProfileComponent(v HelmApplicationDeploymentProfileComponent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsComposeApplicationDeploymentProfileComponent returns the union data inside the AppDeploymentProfile_Components_Item as a ComposeApplicationDeploymentProfileComponent
func (t AppDeploymentProfile_Components_Item) AsComposeApplicationDeploymentProfileComponent() (ComposeApplicationDeploymentProfileComponent, error) {
	var body ComposeApplicationDeploymentProfileComponent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromComposeApplicationDeploymentProfileComponent overwrites any union data inside the AppDeploymentProfile_Components_Item as the provided ComposeApplicationDeploymentProfileComponent
func (t *AppDeploymentProfile_Components_Item) FromComposeApplicationDeploymentProfileComponent(v ComposeApplicationDeploymentProfileComponent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeComposeApplicationDeploymentProfileComponent performs a merge with any union data inside the AppDeploymentProfile_Components_Item, using the provided ComposeApplicationDeploymentProfileComponent
func (t *AppDeploymentProfile_Components_Item) MergeComposeApplicationDeploymentProfileComponent(v ComposeApplicationDeploymentProfileComponent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t AppDeploymentProfile_Components_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AppDeploymentProfile_Components_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
