// Package sbi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package sbi

const (
	Margo_authScopes = "margo_auth.Scopes"
)

// Defines values for AppStateAppState.
const (
	AppStateAppStateCRASHLOOP AppStateAppState = "CRASHLOOP"
	AppStateAppStateREMOVE    AppStateAppState = "REMOVE"
	AppStateAppStateRUNNING   AppStateAppState = "RUNNING"
	AppStateAppStateSTOPPED   AppStateAppState = "STOPPED"
	AppStateAppStateUPDATING  AppStateAppState = "UPDATING"
)

// Defines values for StateParamsDeviceState.
const (
	StateParamsDeviceStateINITIALIZING StateParamsDeviceState = "INITIALIZING"
	StateParamsDeviceStateREBOOTING    StateParamsDeviceState = "REBOOTING"
	StateParamsDeviceStateRUNNING      StateParamsDeviceState = "RUNNING"
	StateParamsDeviceStateSTOPPED      StateParamsDeviceState = "STOPPED"
	StateParamsDeviceStateUPDATING     StateParamsDeviceState = "UPDATING"
)

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// AppState defines model for appState.
type AppState struct {
	// AppDeploymentYAML Base64 encoded MARGO ApplicationDescription YAML content
	AppDeploymentYAML *string `json:"appDeploymentYAML,omitempty"`

	// AppDeploymentYAMLHash App Hash encoding used for versioning the MARGO ApplicationDescription
	AppDeploymentYAMLHash string           `json:"appDeploymentYAMLHash"`
	AppId                 string           `json:"appId"`
	AppState              AppStateAppState `json:"appState"`

	// AppVersion Version String
	AppVersion string `json:"appVersion"`
}

// AppStateAppState defines model for AppState.AppState.
type AppStateAppState string

// CurrentAppStates defines model for currentAppStates.
type CurrentAppStates = []AppState

// DesiredAppStates defines model for desiredAppStates.
type DesiredAppStates = []AppState

// PrivatePayload defines model for privatePayload.
type PrivatePayload struct {
	Code *string `json:"code,omitempty"`
}

// UserArray defines model for UserArray.
type UserArray = []string

// ProcessParams defines parameters for Process.
type ProcessParams struct {
	// DeviceId Device Identifier
	DeviceId *string `form:"deviceId,omitempty" json:"deviceId,omitempty"`

	// RpcId An RPC call to the WFM, initiated by the Device
	RpcId *int `form:"rpcId,omitempty" json:"rpcId,omitempty"`
}

// StateParams defines parameters for State.
type StateParams struct {
	// DeviceId Device Identifier
	DeviceId *string `form:"deviceId,omitempty" json:"deviceId,omitempty"`

	// DeviceState Statusof the device
	DeviceState StateParamsDeviceState `form:"deviceState" json:"deviceState"`

	// RpcId An RPC call to the WFM, initiated by the Device
	RpcId *int `form:"rpcId,omitempty" json:"rpcId,omitempty"`
}

// StateParamsDeviceState defines parameters for State.
type StateParamsDeviceState string

// ProcessJSONRequestBody defines body for Process for application/json ContentType.
type ProcessJSONRequestBody = PrivatePayload

// StateJSONRequestBody defines body for State for application/json ContentType.
type StateJSONRequestBody = CurrentAppStates
