// Package sbi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package sbi

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	Api_keyScopes    = "api_key.Scopes"
	Margo_authScopes = "margo_auth.Scopes"
)

// Defines values for ComponentStatusState.
const (
	ComponentStatusStateFailed     ComponentStatusState = "Failed"
	ComponentStatusStateInstalled  ComponentStatusState = "Installed"
	ComponentStatusStateInstalling ComponentStatusState = "Installing"
	ComponentStatusStatePending    ComponentStatusState = "Pending"
)

// Defines values for OverallStatusState.
const (
	OverallStatusStateFailed     OverallStatusState = "Failed"
	OverallStatusStateInstalled  OverallStatusState = "Installed"
	OverallStatusStateInstalling OverallStatusState = "Installing"
	OverallStatusStatePending    OverallStatusState = "Pending"
)

// Defines values for PropertiesRoles.
const (
	ClusterLead       PropertiesRoles = "cluster lead"
	StandaloneCluster PropertiesRoles = "standalone cluster"
	StandaloneDevice  PropertiesRoles = "standalone device"
)

// Defines values for AppDeploymentProfileType.
const (
	Compose AppDeploymentProfileType = "compose"
	HelmV3  AppDeploymentProfileType = "helm.v3"
)

// Defines values for AppStateAppState.
const (
	CRASHLOOP AppStateAppState = "CRASHLOOP"
	PENDING   AppStateAppState = "PENDING"
	REMOVING  AppStateAppState = "REMOVING"
	RUNNING   AppStateAppState = "RUNNING"
	STOPPED   AppStateAppState = "STOPPED"
	UPDATING  AppStateAppState = "UPDATING"
)

// CPU Defines the CPU characteristics.
type CPU struct {
	// Cores Defines the cores available within the hosts CPU.
	Cores int32 `json:"cores"`

	// CpuArchitecture Defines the CPUs architecture. i.e. ARM/Intel x86.
	CpuArchitecture string `json:"cpuArchitecture"`

	// Frequency Defines the frequency of the CPU in GHz.
	Frequency float32 `json:"frequency"`
}

// ComponentStatus Defines the status of a single deployment component.
type ComponentStatus struct {
	// Error Defines an error that occurred.
	Error *Error `json:"error,omitempty"`

	// Name Name of the deployment component (inherited from the deployment specification).
	Name string `json:"name"`

	// State The component's current deployment state.
	State ComponentStatusState `json:"state"`
}

// ComponentStatusState The component's current deployment state.
type ComponentStatusState string

// DeploymentStatus Reports the status of a deployment.
type DeploymentStatus struct {
	// ApiVersion Identifier of the version of the API the object definition follows.
	ApiVersion string `json:"apiVersion"`

	// Components Individual component deployment statuses.
	Components []ComponentStatus `json:"components"`

	// DeploymentId The unique identifier UUID of the deployment specification.
	DeploymentId openapi_types.UUID `json:"deploymentId"`

	// Kind Must be DeploymentStatus.
	Kind string `json:"kind"`

	// Status Defines the overall deployment status.
	Status OverallStatus `json:"status"`
}

// DeviceCapabilities Reports the capabilities of a device.
type DeviceCapabilities struct {
	// ApiVersion Identifier of the version of the API the object definition follows.
	ApiVersion string `json:"apiVersion"`

	// Kind Must be DeviceCapabilities.
	Kind string `json:"kind"`

	// Properties Defines characteristics about the device.
	Properties Properties `json:"properties"`
}

// Error Defines an error that occurred.
type Error struct {
	// Code Associated error code.
	Code *string `json:"code,omitempty"`

	// Message Associated error message.
	Message *string `json:"message,omitempty"`
}

// Interface Defines a device interface.
type Interface struct {
	// ModelNumber Model number of the interface.
	ModelNumber string `json:"modelNumber"`

	// Name Name of the interface.
	Name string `json:"name"`

	// Properties Properties of the interface to inform the WOS with additional information.
	Properties map[string]string `json:"properties"`

	// Type Type of the interface. i.e. Ethernet NIC
	Type string `json:"type"`
}

// OnboardingRequest Request body for the /onboarding/device endpoint.
type OnboardingRequest = map[string]interface{}

// OnboardingResponse Response body for the /onboarding/device endpoint.
type OnboardingResponse struct {
	// ClientId The client ID for OAuth 2.0 authentication.
	ClientId string `json:"clientId"`

	// ClientSecret The client secret for OAuth 2.0 authentication.
	ClientSecret string `json:"clientSecret"`

	// GitAccessToken An access token for authenticating with the Git repository.
	GitAccessToken string `json:"gitAccessToken"`

	// GitRepositoryUrl The URL for the Git repository containing the desired state.
	GitRepositoryUrl string `json:"gitRepositoryUrl"`

	// TokenEndpointUrl The URL for the OAuth 2.0 token endpoint.
	TokenEndpointUrl string `json:"tokenEndpointUrl"`
}

// OverallStatus Defines the overall deployment status.
type OverallStatus struct {
	// Error Defines an error that occurred.
	Error *Error `json:"error,omitempty"`

	// State Current state of the overall deployment.
	State OverallStatusState `json:"state"`
}

// OverallStatusState Current state of the overall deployment.
type OverallStatusState string

// Peripheral Defines a device peripheral.
type Peripheral struct {
	// ModelNumber Model number of the peripheral.
	ModelNumber string `json:"modelNumber"`

	// Name Name of the peripheral.
	Name string `json:"name"`

	// Properties Properties of the peripheral.
	Properties map[string]string `json:"properties"`

	// Type Type of the peripheral. i.e. GPU
	Type string `json:"type"`
}

// Properties Defines characteristics about the device.
type Properties struct {
	// Id Unique deviceID assigned to the device via the Device Owner.
	Id string `json:"id"`

	// Interfaces Defines the device's interfaces that are available to the application deployed on the device.
	Interfaces []Interface `json:"interfaces"`

	// ModelNumber Defines the model number of the device.
	ModelNumber string `json:"modelNumber"`

	// Peripherals Defines the device's peripherals available to the application deployed on the device.
	Peripherals []Peripheral `json:"peripherals"`

	// Resources Defines the device's resources available to the application deployed on the device.
	Resources Resources `json:"resources"`

	// Roles Defines the device role it can provide to the Margo environment.
	Roles []PropertiesRoles `json:"roles"`

	// SerialNumber Defines the serial number of the device.
	SerialNumber string `json:"serialNumber"`

	// Vendor Defines the device vendor.
	Vendor string `json:"vendor"`
}

// PropertiesRoles defines model for Properties.Roles.
type PropertiesRoles string

// Resources Defines the device's resources available to the application deployed on the device.
type Resources struct {
	// Cpus Defines the device's CPUs that are available to the application deployed on the device.
	Cpus []CPU `json:"cpus"`

	// Memory Defines the memory capacity available for applications on the device in GBs.
	Memory int32 `json:"memory"`

	// Storage Defines the storage capacity available for applications to utilize in GBs.
	Storage int32 `json:"storage"`
}

// AppDeployment Application Deployment manifest
type AppDeployment struct {
	// ApiVersion API version
	ApiVersion string `json:"apiVersion"`

	// Kind Resource kind
	Kind     string                `json:"kind"`
	Metadata AppDeploymentMetadata `json:"metadata"`

	// Spec Application Deployment specification
	Spec AppDeploymentSpec `json:"spec"`
}

// AppDeploymentMetadata defines model for appDeploymentMetadata.
type AppDeploymentMetadata struct {
	// Annotations Annotations for the resource
	Annotations *map[string]string `json:"annotations,omitempty"`

	// Id Unique identifier for the application deployment
	Id *string `json:"id,omitempty"`

	// Labels Labels for the resource
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Name of the resource
	Name string `json:"name"`

	// Namespace Namespace of the resource
	Namespace *string `json:"namespace,omitempty"`
}

// AppDeploymentParams Application Parameters
type AppDeploymentParams map[string]AppParameterValue

// AppDeploymentProfile Application Deployment Profile
type AppDeploymentProfile struct {
	// Components Components of the deployment profile
	Components []AppDeploymentProfile_Components_Item `json:"components"`

	// Type Type of deployment profile
	Type AppDeploymentProfileType `json:"type"`
}

// AppDeploymentProfile_Components_Item defines model for appDeploymentProfile.components.Item.
type AppDeploymentProfile_Components_Item struct {
	union json.RawMessage
}

// AppDeploymentProfileType Type of deployment profile
type AppDeploymentProfileType string

// AppDeploymentSpec Application Deployment specification
type AppDeploymentSpec struct {
	// DeploymentProfile Application Deployment Profile
	DeploymentProfile AppDeploymentProfile `json:"deploymentProfile"`

	// Parameters Application Parameters
	Parameters *AppDeploymentParams `json:"parameters,omitempty"`
}

// AppParameterTarget Application Parameter Target
type AppParameterTarget struct {
	// Components Components of the parameter
	Components []string `json:"components"`

	// Pointer Pointer to the parameter
	Pointer string `json:"pointer"`
}

// AppParameterValue Application Parameter Value
type AppParameterValue struct {
	// Targets Targets of the parameter
	Targets []AppParameterTarget `json:"targets"`

	// Value Value of the parameter
	Value string `json:"value"`
}

// AppState defines model for appState.
type AppState struct {
	// AppDeploymentYAML Base64 encoded MARGO ApplicationDescription YAML content
	AppDeploymentYAML *string `json:"appDeploymentYAML,omitempty"`

	// AppDeploymentYAMLHash App Hash encoding used for versioning the MARGO ApplicationDescription
	AppDeploymentYAMLHash string           `json:"appDeploymentYAMLHash"`
	AppId                 string           `json:"appId"`
	AppState              AppStateAppState `json:"appState"`

	// AppVersion Version String
	AppVersion string `json:"appVersion"`
}

// AppStateAppState defines model for AppState.AppState.
type AppStateAppState string

// ComposeApplicationDeploymentProfileComponent Compose Application Deployment Profile Component
type ComposeApplicationDeploymentProfileComponent struct {
	// Name Name of the component
	Name       string `json:"name"`
	Properties struct {
		// KeyLocation Key location of the component
		KeyLocation *string `json:"keyLocation,omitempty"`

		// PackageLocation Package location of the component
		PackageLocation string `json:"packageLocation"`

		// Timeout Timeout for the component
		Timeout *string `json:"timeout,omitempty"`

		// Wait Wait for the component to be ready
		Wait *bool `json:"wait,omitempty"`
	} `json:"properties"`
}

// CurrentAppStates defines model for currentAppStates.
type CurrentAppStates = []AppState

// DesiredAppStates defines model for desiredAppStates.
type DesiredAppStates = []AppState

// HelmApplicationDeploymentProfileComponent Helm Application Deployment Profile Component
type HelmApplicationDeploymentProfileComponent struct {
	// Name Name of the component
	Name       string `json:"name"`
	Properties struct {
		// Repository Repository of the component
		Repository string `json:"repository"`

		// Revision Revision of the component
		Revision *string `json:"revision,omitempty"`

		// Timeout Timeout for the component
		Timeout *string `json:"timeout,omitempty"`

		// Wait Wait for the component to be ready
		Wait *bool `json:"wait,omitempty"`
	} `json:"properties"`
}

// PrivatePayload defines model for privatePayload.
type PrivatePayload struct {
	Code *string `json:"code,omitempty"`
}

// UserArray defines model for UserArray.
type UserArray = []string

// ProcessParams defines parameters for Process.
type ProcessParams struct {
	// RpcId An RPC call to the WFM, initiated by the Device
	RpcId *int `form:"rpcId,omitempty" json:"rpcId,omitempty"`
}

// PostDeviceDeviceIdCapabilitiesJSONRequestBody defines body for PostDeviceDeviceIdCapabilities for application/json ContentType.
type PostDeviceDeviceIdCapabilitiesJSONRequestBody = DeviceCapabilities

// PutDeviceDeviceIdCapabilitiesJSONRequestBody defines body for PutDeviceDeviceIdCapabilities for application/json ContentType.
type PutDeviceDeviceIdCapabilitiesJSONRequestBody = DeviceCapabilities

// PostDeviceDeviceIdDeploymentDeploymentIdStatusJSONRequestBody defines body for PostDeviceDeviceIdDeploymentDeploymentIdStatus for application/json ContentType.
type PostDeviceDeviceIdDeploymentDeploymentIdStatusJSONRequestBody = DeploymentStatus

// PostOnboardingDeviceJSONRequestBody defines body for PostOnboardingDevice for application/json ContentType.
type PostOnboardingDeviceJSONRequestBody = OnboardingRequest

// ProcessJSONRequestBody defines body for Process for application/json ContentType.
type ProcessJSONRequestBody = PrivatePayload

// StateJSONRequestBody defines body for State for application/json ContentType.
type StateJSONRequestBody = CurrentAppStates

// AsHelmApplicationDeploymentProfileComponent returns the union data inside the AppDeploymentProfile_Components_Item as a HelmApplicationDeploymentProfileComponent
func (t AppDeploymentProfile_Components_Item) AsHelmApplicationDeploymentProfileComponent() (HelmApplicationDeploymentProfileComponent, error) {
	var body HelmApplicationDeploymentProfileComponent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromHelmApplicationDeploymentProfileComponent overwrites any union data inside the AppDeploymentProfile_Components_Item as the provided HelmApplicationDeploymentProfileComponent
func (t *AppDeploymentProfile_Components_Item) FromHelmApplicationDeploymentProfileComponent(v HelmApplicationDeploymentProfileComponent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeHelmApplicationDeploymentProfileComponent performs a merge with any union data inside the AppDeploymentProfile_Components_Item, using the provided HelmApplicationDeploymentProfileComponent
func (t *AppDeploymentProfile_Components_Item) MergeHelmApplicationDeploymentProfileComponent(v HelmApplicationDeploymentProfileComponent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsComposeApplicationDeploymentProfileComponent returns the union data inside the AppDeploymentProfile_Components_Item as a ComposeApplicationDeploymentProfileComponent
func (t AppDeploymentProfile_Components_Item) AsComposeApplicationDeploymentProfileComponent() (ComposeApplicationDeploymentProfileComponent, error) {
	var body ComposeApplicationDeploymentProfileComponent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromComposeApplicationDeploymentProfileComponent overwrites any union data inside the AppDeploymentProfile_Components_Item as the provided ComposeApplicationDeploymentProfileComponent
func (t *AppDeploymentProfile_Components_Item) FromComposeApplicationDeploymentProfileComponent(v ComposeApplicationDeploymentProfileComponent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeComposeApplicationDeploymentProfileComponent performs a merge with any union data inside the AppDeploymentProfile_Components_Item, using the provided ComposeApplicationDeploymentProfileComponent
func (t *AppDeploymentProfile_Components_Item) MergeComposeApplicationDeploymentProfileComponent(v ComposeApplicationDeploymentProfileComponent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t AppDeploymentProfile_Components_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AppDeploymentProfile_Components_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
