// Package sbi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package sbi

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for AuthChallengeResponseStatus.
const (
	Failed        AuthChallengeResponseStatus = "failed"
	Passed        AuthChallengeResponseStatus = "passed"
	RetryRequired AuthChallengeResponseStatus = "retry_required"
)

// Defines values for AuthProtocolType.
const (
	AuthProtocolTypeFIDO AuthProtocolType = "FIDO"
	AuthProtocolTypePKI  AuthProtocolType = "PKI"
)

// Defines values for CredentialStatus.
const (
	CredentialStatusActive  CredentialStatus = "active"
	CredentialStatusExpired CredentialStatus = "expired"
	CredentialStatusRevoked CredentialStatus = "revoked"
)

// Defines values for CredentialType.
const (
	CredentialTypeFIDO CredentialType = "FIDO"
	CredentialTypePKI  CredentialType = "PKI"
)

// Defines values for DeviceOnboardingResponseStatus.
const (
	ChallengeRequired DeviceOnboardingResponseStatus = "challenge_required"
	Initiated         DeviceOnboardingResponseStatus = "initiated"
	Onboarded         DeviceOnboardingResponseStatus = "onboarded"
)

// Defines values for DeviceOperation.
const (
	DEBOARD        DeviceOperation = "DEBOARD"
	ONBOARD        DeviceOperation = "ONBOARD"
	RESET          DeviceOperation = "RESET"
	RESTART        DeviceOperation = "RESTART"
	SHUTDOWN       DeviceOperation = "SHUTDOWN"
	START          DeviceOperation = "START"
	UPDATEFIRMWARE DeviceOperation = "UPDATE_FIRMWARE"
)

// Defines values for DeviceOperationStatus.
const (
	CANCELLED DeviceOperationStatus = "CANCELLED"
	COMPLETED DeviceOperationStatus = "COMPLETED"
	FAILED    DeviceOperationStatus = "FAILED"
	PENDING   DeviceOperationStatus = "PENDING"
	REJECTED  DeviceOperationStatus = "REJECTED"
	SCHEDULED DeviceOperationStatus = "SCHEDULED"
	TIMEOUT   DeviceOperationStatus = "TIMEOUT"
)

// Defines values for DeviceProfileStatus.
const (
	DeviceProfileStatusActive    DeviceProfileStatus = "active"
	DeviceProfileStatusInactive  DeviceProfileStatus = "inactive"
	DeviceProfileStatusSuspended DeviceProfileStatus = "suspended"
)

// Defines values for DeviceStatusState.
const (
	BOOTING          DeviceStatusState = "BOOTING"
	DEBOARDED        DeviceStatusState = "DEBOARDED"
	ERROR            DeviceStatusState = "ERROR"
	OFFLINE          DeviceStatusState = "OFFLINE"
	ONBOARDED        DeviceStatusState = "ONBOARDED"
	ONLINE           DeviceStatusState = "ONLINE"
	UNDERMAINTENANCE DeviceStatusState = "UNDER_MAINTENANCE"
)

// Defines values for FIDO2ParametersAuthenticatorSelectionAuthenticatorAttachment.
const (
	CrossPlatform FIDO2ParametersAuthenticatorSelectionAuthenticatorAttachment = "cross-platform"
	Platform      FIDO2ParametersAuthenticatorSelectionAuthenticatorAttachment = "platform"
)

// Defines values for FIDO2ParametersAuthenticatorSelectionUserVerification.
const (
	FIDO2ParametersAuthenticatorSelectionUserVerificationDiscouraged FIDO2ParametersAuthenticatorSelectionUserVerification = "discouraged"
	FIDO2ParametersAuthenticatorSelectionUserVerificationPreferred   FIDO2ParametersAuthenticatorSelectionUserVerification = "preferred"
	FIDO2ParametersAuthenticatorSelectionUserVerificationRequired    FIDO2ParametersAuthenticatorSelectionUserVerification = "required"
)

// Defines values for FIDO2ParametersUserVerification.
const (
	FIDO2ParametersUserVerificationDiscouraged FIDO2ParametersUserVerification = "discouraged"
	FIDO2ParametersUserVerificationPreferred   FIDO2ParametersUserVerification = "preferred"
	FIDO2ParametersUserVerificationRequired    FIDO2ParametersUserVerification = "required"
)

// Defines values for OnboardingNextStepAction.
const (
	Authenticate OnboardingNextStepAction = "authenticate"
	Complete     OnboardingNextStepAction = "complete"
	Wait         OnboardingNextStepAction = "wait"
)

// Defines values for PKIParametersAlgorithm.
const (
	ECDSA PKIParametersAlgorithm = "ECDSA"
	RSA   PKIParametersAlgorithm = "RSA"
)

// Defines values for PKIParametersKeySize.
const (
	N2048 PKIParametersKeySize = 2048
	N4096 PKIParametersKeySize = 4096
)

// APIResponse defines model for APIResponse.
type APIResponse struct {
	RequestId string    `json:"requestId"`
	Timestamp time.Time `json:"timestamp"`
}

// AuthChallengeRequest defines model for AuthChallengeRequest.
type AuthChallengeRequest struct {
	Response  AuthChallengeRequest_Response `json:"response"`
	SessionId string                        `json:"sessionId"`
}

// AuthChallengeRequest_Response defines model for AuthChallengeRequest.Response.
type AuthChallengeRequest_Response struct {
	union json.RawMessage
}

// AuthChallengeResponse defines model for AuthChallengeResponse.
type AuthChallengeResponse struct {
	NextStep  *OnboardingNextStep          `json:"nextStep,omitempty"`
	SessionId *string                      `json:"sessionId,omitempty"`
	Status    *AuthChallengeResponseStatus `json:"status,omitempty"`
}

// AuthChallengeResponseStatus defines model for AuthChallengeResponse.Status.
type AuthChallengeResponseStatus string

// AuthProtocol defines model for AuthProtocol.
type AuthProtocol struct {
	Parameters *AuthProtocol_Parameters `json:"parameters,omitempty"`
	Type       AuthProtocolType         `json:"type"`
	Version    *string                  `json:"version,omitempty"`
}

// AuthProtocol_Parameters defines model for AuthProtocol.Parameters.
type AuthProtocol_Parameters struct {
	union json.RawMessage
}

// AuthProtocolType defines model for AuthProtocol.Type.
type AuthProtocolType string

// ContextualInfo defines model for ContextualInfo.
type ContextualInfo struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// Credential defines model for Credential.
type Credential struct {
	CreatedAt *time.Time        `json:"createdAt,omitempty"`
	ExpiresAt *time.Time        `json:"expiresAt,omitempty"`
	Id        *string           `json:"id,omitempty"`
	Status    *CredentialStatus `json:"status,omitempty"`
	Type      *CredentialType   `json:"type,omitempty"`
}

// CredentialStatus defines model for Credential.Status.
type CredentialStatus string

// CredentialType defines model for Credential.Type.
type CredentialType string

// Device defines model for Device.
type Device struct {
	ApiVersion      string                 `json:"apiVersion"`
	Kind            string                 `json:"kind"`
	Metadata        Device_Metadata        `json:"metadata"`
	RecentOperation *DeviceRecentOperation `json:"recentOperation,omitempty"`
	Spec            struct {
		Protocol *AuthProtocol `json:"protocol,omitempty"`
	} `json:"spec"`
	Status *DeviceStatus `json:"status,omitempty"`
}

// Device_Metadata defines model for Device.Metadata.
type Device_Metadata struct {
	Annotations       *map[string]string `json:"annotations,omitempty"`
	CreationTimestamp *time.Time         `json:"creationTimestamp,omitempty"`

	// Id This field is generated by the server.
	Id                   *string                `json:"id,omitempty"`
	Labels               *map[string]string     `json:"labels,omitempty"`
	Name                 *string                `json:"name,omitempty"`
	Namespace            *string                `json:"namespace,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// DeviceOnboardingCompletionRequest defines model for DeviceOnboardingCompletionRequest.
type DeviceOnboardingCompletionRequest struct {
	DeviceName *string   `json:"deviceName,omitempty"`
	Policies   *[]string `json:"policies,omitempty"`
	SessionId  string    `json:"sessionId"`
}

// DeviceOnboardingRequest defines model for DeviceOnboardingRequest.
type DeviceOnboardingRequest struct {
	ApiVersion string                           `json:"apiVersion"`
	Kind       string                           `json:"kind"`
	Metadata   DeviceOnboardingRequest_Metadata `json:"metadata"`
	Spec       struct {
		Protocol *AuthProtocol `json:"protocol,omitempty"`
	} `json:"spec"`
}

// DeviceOnboardingRequest_Metadata defines model for DeviceOnboardingRequest.Metadata.
type DeviceOnboardingRequest_Metadata struct {
	Annotations          *map[string]string     `json:"annotations,omitempty"`
	Labels               *map[string]string     `json:"labels,omitempty"`
	Name                 *string                `json:"name,omitempty"`
	Namespace            *string                `json:"namespace,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// DeviceOnboardingResponse defines model for DeviceOnboardingResponse.
type DeviceOnboardingResponse struct {
	DeviceId  string                         `json:"deviceId"`
	ExpiresAt *time.Time                     `json:"expiresAt,omitempty"`
	NextStep  *OnboardingNextStep            `json:"nextStep,omitempty"`
	SessionId string                         `json:"sessionId"`
	Status    DeviceOnboardingResponseStatus `json:"status"`
}

// DeviceOnboardingResponseStatus defines model for DeviceOnboardingResponse.Status.
type DeviceOnboardingResponseStatus string

// DeviceOperation defines model for DeviceOperation.
type DeviceOperation string

// DeviceOperationStatus defines model for DeviceOperationStatus.
type DeviceOperationStatus string

// DeviceProfile defines model for DeviceProfile.
type DeviceProfile struct {
	Credentials *[]Credential        `json:"credentials,omitempty"`
	DeviceId    *string              `json:"deviceId,omitempty"`
	OnboardedAt *time.Time           `json:"onboardedAt,omitempty"`
	Policies    *[]string            `json:"policies,omitempty"`
	Status      *DeviceProfileStatus `json:"status,omitempty"`
}

// DeviceProfileStatus defines model for DeviceProfile.Status.
type DeviceProfileStatus string

// DeviceRecentOperation defines model for DeviceRecentOperation.
type DeviceRecentOperation struct {
	Op     DeviceOperation       `json:"op"`
	Status DeviceOperationStatus `json:"status"`
}

// DeviceStatus defines model for DeviceStatus.
type DeviceStatus struct {
	ContextualInfo *ContextualInfo    `json:"contextualInfo,omitempty"`
	LastUpdateTime *time.Time         `json:"lastUpdateTime,omitempty"`
	State          *DeviceStatusState `json:"state,omitempty"`
}

// DeviceStatusState defines model for DeviceStatus.State.
type DeviceStatusState string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Details   *map[string]interface{} `json:"details,omitempty"`
	ErrorCode string                  `json:"errorCode"`
	RequestId string                  `json:"requestId"`
	Timestamp time.Time               `json:"timestamp"`
}

// FIDO2Parameters defines model for FIDO2Parameters.
type FIDO2Parameters struct {
	AuthenticatorSelection *struct {
		AuthenticatorAttachment *FIDO2ParametersAuthenticatorSelectionAuthenticatorAttachment `json:"authenticatorAttachment,omitempty"`
		UserVerification        *FIDO2ParametersAuthenticatorSelectionUserVerification        `json:"userVerification,omitempty"`
	} `json:"authenticatorSelection,omitempty"`
	Challenge        *[]byte                          `json:"challenge,omitempty"`
	RpId             *string                          `json:"rpId,omitempty"`
	UserVerification *FIDO2ParametersUserVerification `json:"userVerification,omitempty"`
}

// FIDO2ParametersAuthenticatorSelectionAuthenticatorAttachment defines model for FIDO2Parameters.AuthenticatorSelection.AuthenticatorAttachment.
type FIDO2ParametersAuthenticatorSelectionAuthenticatorAttachment string

// FIDO2ParametersAuthenticatorSelectionUserVerification defines model for FIDO2Parameters.AuthenticatorSelection.UserVerification.
type FIDO2ParametersAuthenticatorSelectionUserVerification string

// FIDO2ParametersUserVerification defines model for FIDO2Parameters.UserVerification.
type FIDO2ParametersUserVerification string

// FIDO2Response defines model for FIDO2Response.
type FIDO2Response struct {
	AuthenticatorData *[]byte `json:"authenticatorData,omitempty"`
	ClientDataJSON    *[]byte `json:"clientDataJSON,omitempty"`
	Signature         *[]byte `json:"signature,omitempty"`
	UserHandle        *[]byte `json:"userHandle,omitempty"`
}

// FIDOParameters defines model for FIDOParameters.
type FIDOParameters struct {
	AppId     *string `json:"appId,omitempty"`
	Challenge *[]byte `json:"challenge,omitempty"`
	KeyHandle *[]byte `json:"keyHandle,omitempty"`
}

// FIDOResponse defines model for FIDOResponse.
type FIDOResponse struct {
	ApplicationParameter *[]byte `json:"applicationParameter,omitempty"`
	ClientData           *[]byte `json:"clientData,omitempty"`
	Signature            *[]byte `json:"signature,omitempty"`
}

// JWTParameters defines model for JWTParameters.
type JWTParameters struct {
	Audience *string `json:"audience,omitempty"`
	Issuer   *string `json:"issuer,omitempty"`
	Token    *string `json:"token,omitempty"`
}

// OAuth2Parameters defines model for OAuth2Parameters.
type OAuth2Parameters struct {
	ClientId    *string `json:"clientId,omitempty"`
	RedirectUri *string `json:"redirectUri,omitempty"`
	Scope       *string `json:"scope,omitempty"`
}

// OnboardingNextStep defines model for OnboardingNextStep.
type OnboardingNextStep struct {
	Action     *OnboardingNextStepAction `json:"action,omitempty"`
	Endpoint   *string                   `json:"endpoint,omitempty"`
	Parameters *map[string]interface{}   `json:"parameters,omitempty"`
}

// OnboardingNextStepAction defines model for OnboardingNextStep.Action.
type OnboardingNextStepAction string

// PKIParameters defines model for PKIParameters.
type PKIParameters struct {
	Algorithm            *PKIParametersAlgorithm `json:"algorithm,omitempty"`
	CertificateAuthority *string                 `json:"certificateAuthority,omitempty"`
	Csr                  *[]byte                 `json:"csr,omitempty"`
	KeySize              *PKIParametersKeySize   `json:"keySize,omitempty"`
}

// PKIParametersAlgorithm defines model for PKIParameters.Algorithm.
type PKIParametersAlgorithm string

// PKIParametersKeySize defines model for PKIParameters.KeySize.
type PKIParametersKeySize int

// PKIResponse defines model for PKIResponse.
type PKIResponse struct {
	Certificate     *[]byte `json:"certificate,omitempty"`
	PrivateKeyProof *[]byte `json:"privateKeyProof,omitempty"`
}

// OnboardDeviceJSONRequestBody defines body for OnboardDevice for application/json ContentType.
type OnboardDeviceJSONRequestBody = DeviceOnboardingRequest

// DeviceChallengeJSONRequestBody defines body for DeviceChallenge for application/json ContentType.
type DeviceChallengeJSONRequestBody = AuthChallengeRequest

// CompleteDeviceOnboardingJSONRequestBody defines body for CompleteDeviceOnboarding for application/json ContentType.
type CompleteDeviceOnboardingJSONRequestBody = DeviceOnboardingCompletionRequest

// Getter for additional properties for Device_Metadata. Returns the specified
// element and whether it was found
func (a Device_Metadata) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Device_Metadata
func (a *Device_Metadata) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Device_Metadata to handle AdditionalProperties
func (a *Device_Metadata) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["annotations"]; found {
		err = json.Unmarshal(raw, &a.Annotations)
		if err != nil {
			return fmt.Errorf("error reading 'annotations': %w", err)
		}
		delete(object, "annotations")
	}

	if raw, found := object["creationTimestamp"]; found {
		err = json.Unmarshal(raw, &a.CreationTimestamp)
		if err != nil {
			return fmt.Errorf("error reading 'creationTimestamp': %w", err)
		}
		delete(object, "creationTimestamp")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["labels"]; found {
		err = json.Unmarshal(raw, &a.Labels)
		if err != nil {
			return fmt.Errorf("error reading 'labels': %w", err)
		}
		delete(object, "labels")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["namespace"]; found {
		err = json.Unmarshal(raw, &a.Namespace)
		if err != nil {
			return fmt.Errorf("error reading 'namespace': %w", err)
		}
		delete(object, "namespace")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Device_Metadata to handle AdditionalProperties
func (a Device_Metadata) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Annotations != nil {
		object["annotations"], err = json.Marshal(a.Annotations)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'annotations': %w", err)
		}
	}

	if a.CreationTimestamp != nil {
		object["creationTimestamp"], err = json.Marshal(a.CreationTimestamp)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'creationTimestamp': %w", err)
		}
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.Labels != nil {
		object["labels"], err = json.Marshal(a.Labels)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'labels': %w", err)
		}
	}

	if a.Name != nil {
		object["name"], err = json.Marshal(a.Name)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'name': %w", err)
		}
	}

	if a.Namespace != nil {
		object["namespace"], err = json.Marshal(a.Namespace)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'namespace': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for DeviceOnboardingRequest_Metadata. Returns the specified
// element and whether it was found
func (a DeviceOnboardingRequest_Metadata) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for DeviceOnboardingRequest_Metadata
func (a *DeviceOnboardingRequest_Metadata) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for DeviceOnboardingRequest_Metadata to handle AdditionalProperties
func (a *DeviceOnboardingRequest_Metadata) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["annotations"]; found {
		err = json.Unmarshal(raw, &a.Annotations)
		if err != nil {
			return fmt.Errorf("error reading 'annotations': %w", err)
		}
		delete(object, "annotations")
	}

	if raw, found := object["labels"]; found {
		err = json.Unmarshal(raw, &a.Labels)
		if err != nil {
			return fmt.Errorf("error reading 'labels': %w", err)
		}
		delete(object, "labels")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["namespace"]; found {
		err = json.Unmarshal(raw, &a.Namespace)
		if err != nil {
			return fmt.Errorf("error reading 'namespace': %w", err)
		}
		delete(object, "namespace")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for DeviceOnboardingRequest_Metadata to handle AdditionalProperties
func (a DeviceOnboardingRequest_Metadata) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Annotations != nil {
		object["annotations"], err = json.Marshal(a.Annotations)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'annotations': %w", err)
		}
	}

	if a.Labels != nil {
		object["labels"], err = json.Marshal(a.Labels)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'labels': %w", err)
		}
	}

	if a.Name != nil {
		object["name"], err = json.Marshal(a.Name)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'name': %w", err)
		}
	}

	if a.Namespace != nil {
		object["namespace"], err = json.Marshal(a.Namespace)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'namespace': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsPKIResponse returns the union data inside the AuthChallengeRequest_Response as a PKIResponse
func (t AuthChallengeRequest_Response) AsPKIResponse() (PKIResponse, error) {
	var body PKIResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPKIResponse overwrites any union data inside the AuthChallengeRequest_Response as the provided PKIResponse
func (t *AuthChallengeRequest_Response) FromPKIResponse(v PKIResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePKIResponse performs a merge with any union data inside the AuthChallengeRequest_Response, using the provided PKIResponse
func (t *AuthChallengeRequest_Response) MergePKIResponse(v PKIResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsFIDOResponse returns the union data inside the AuthChallengeRequest_Response as a FIDOResponse
func (t AuthChallengeRequest_Response) AsFIDOResponse() (FIDOResponse, error) {
	var body FIDOResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFIDOResponse overwrites any union data inside the AuthChallengeRequest_Response as the provided FIDOResponse
func (t *AuthChallengeRequest_Response) FromFIDOResponse(v FIDOResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFIDOResponse performs a merge with any union data inside the AuthChallengeRequest_Response, using the provided FIDOResponse
func (t *AuthChallengeRequest_Response) MergeFIDOResponse(v FIDOResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t AuthChallengeRequest_Response) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AuthChallengeRequest_Response) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsPKIParameters returns the union data inside the AuthProtocol_Parameters as a PKIParameters
func (t AuthProtocol_Parameters) AsPKIParameters() (PKIParameters, error) {
	var body PKIParameters
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPKIParameters overwrites any union data inside the AuthProtocol_Parameters as the provided PKIParameters
func (t *AuthProtocol_Parameters) FromPKIParameters(v PKIParameters) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePKIParameters performs a merge with any union data inside the AuthProtocol_Parameters, using the provided PKIParameters
func (t *AuthProtocol_Parameters) MergePKIParameters(v PKIParameters) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsFIDOParameters returns the union data inside the AuthProtocol_Parameters as a FIDOParameters
func (t AuthProtocol_Parameters) AsFIDOParameters() (FIDOParameters, error) {
	var body FIDOParameters
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFIDOParameters overwrites any union data inside the AuthProtocol_Parameters as the provided FIDOParameters
func (t *AuthProtocol_Parameters) FromFIDOParameters(v FIDOParameters) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFIDOParameters performs a merge with any union data inside the AuthProtocol_Parameters, using the provided FIDOParameters
func (t *AuthProtocol_Parameters) MergeFIDOParameters(v FIDOParameters) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t AuthProtocol_Parameters) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AuthProtocol_Parameters) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
