// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package client

import . "github.com/margo/dev-repo/margo/generatedCode/models"

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// Poke request
	Poke(ctx context.Context, params *PokeParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ProcessWithBody request with any body
	ProcessWithBody(ctx context.Context, params *ProcessParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	Process(ctx context.Context, params *ProcessParams, body ProcessJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StateWithBody request with any body
	StateWithBody(ctx context.Context, params *StateParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	State(ctx context.Context, params *StateParams, body StateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) Poke(ctx context.Context, params *PokeParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPokeRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ProcessWithBody(ctx context.Context, params *ProcessParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewProcessRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Process(ctx context.Context, params *ProcessParams, body ProcessJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewProcessRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StateWithBody(ctx context.Context, params *StateParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStateRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) State(ctx context.Context, params *StateParams, body StateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStateRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPokeRequest generates requests for Poke
func NewPokeRequest(server string, params *PokeParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/device/poke")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "deviceId", runtime.ParamLocationQuery, params.DeviceId); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.RpcId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "rpcId", runtime.ParamLocationQuery, *params.RpcId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewProcessRequest calls the generic Process builder with application/json body
func NewProcessRequest(server string, params *ProcessParams, body ProcessJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewProcessRequestWithBody(server, params, "application/json", bodyReader)
}

// NewProcessRequestWithBody generates requests for Process with any type of body
func NewProcessRequestWithBody(server string, params *ProcessParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/wfm/process")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.DeviceId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "deviceId", runtime.ParamLocationQuery, *params.DeviceId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.RpcId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "rpcId", runtime.ParamLocationQuery, *params.RpcId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewStateRequest calls the generic State builder with application/json body
func NewStateRequest(server string, params *StateParams, body StateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewStateRequestWithBody(server, params, "application/json", bodyReader)
}

// NewStateRequestWithBody generates requests for State with any type of body
func NewStateRequestWithBody(server string, params *StateParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/wfm/state")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.DeviceId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "deviceId", runtime.ParamLocationQuery, *params.DeviceId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "deviceState", runtime.ParamLocationQuery, params.DeviceState); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.RpcId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "rpcId", runtime.ParamLocationQuery, *params.RpcId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PokeWithResponse request
	PokeWithResponse(ctx context.Context, params *PokeParams, reqEditors ...RequestEditorFn) (*PokeResponse, error)

	// ProcessWithBodyWithResponse request with any body
	ProcessWithBodyWithResponse(ctx context.Context, params *ProcessParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ProcessResponse, error)

	ProcessWithResponse(ctx context.Context, params *ProcessParams, body ProcessJSONRequestBody, reqEditors ...RequestEditorFn) (*ProcessResponse, error)

	// StateWithBodyWithResponse request with any body
	StateWithBodyWithResponse(ctx context.Context, params *StateParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*StateResponse, error)

	StateWithResponse(ctx context.Context, params *StateParams, body StateJSONRequestBody, reqEditors ...RequestEditorFn) (*StateResponse, error)
}

type PokeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r PokeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PokeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ProcessResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PrivatePayload
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r ProcessResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ProcessResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type StateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DesiredAppStates
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r StateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PokeWithResponse request returning *PokeResponse
func (c *ClientWithResponses) PokeWithResponse(ctx context.Context, params *PokeParams, reqEditors ...RequestEditorFn) (*PokeResponse, error) {
	rsp, err := c.Poke(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePokeResponse(rsp)
}

// ProcessWithBodyWithResponse request with arbitrary body returning *ProcessResponse
func (c *ClientWithResponses) ProcessWithBodyWithResponse(ctx context.Context, params *ProcessParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ProcessResponse, error) {
	rsp, err := c.ProcessWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseProcessResponse(rsp)
}

func (c *ClientWithResponses) ProcessWithResponse(ctx context.Context, params *ProcessParams, body ProcessJSONRequestBody, reqEditors ...RequestEditorFn) (*ProcessResponse, error) {
	rsp, err := c.Process(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseProcessResponse(rsp)
}

// StateWithBodyWithResponse request with arbitrary body returning *StateResponse
func (c *ClientWithResponses) StateWithBodyWithResponse(ctx context.Context, params *StateParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*StateResponse, error) {
	rsp, err := c.StateWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStateResponse(rsp)
}

func (c *ClientWithResponses) StateWithResponse(ctx context.Context, params *StateParams, body StateJSONRequestBody, reqEditors ...RequestEditorFn) (*StateResponse, error) {
	rsp, err := c.State(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStateResponse(rsp)
}

// ParsePokeResponse parses an HTTP response from a PokeWithResponse call
func ParsePokeResponse(rsp *http.Response) (*PokeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PokeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseProcessResponse parses an HTTP response from a ProcessWithResponse call
func ParseProcessResponse(rsp *http.Response) (*ProcessResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ProcessResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PrivatePayload
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseStateResponse parses an HTTP response from a StateWithResponse call
func ParseStateResponse(rsp *http.Response) (*StateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DesiredAppStates
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
