// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package models

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for AppPkgSourceType.
const (
	AppPkgSourceTypeGITREPO AppPkgSourceType = "GIT_REPO"
)

// Defines values for AppPkgOnboardingReqSourceType.
const (
	AppPkgOnboardingReqSourceTypeGITREPO AppPkgOnboardingReqSourceType = "GIT_REPO"
)

// Defines values for AppPkgOnboardingRespSourceType.
const (
	AppPkgOnboardingRespSourceTypeGITREPO AppPkgOnboardingRespSourceType = "GIT_REPO"
)

// Defines values for AppPkgOperation.
const (
	Deboard AppPkgOperation = "deboard"
	Onboard AppPkgOperation = "onboard"
	Stage   AppPkgOperation = "stage"
	Unstage AppPkgOperation = "unstage"
)

// Defines values for AppPkgOperationState.
const (
	Cancelled  AppPkgOperationState = "cancelled"
	Completed  AppPkgOperationState = "completed"
	Failed     AppPkgOperationState = "failed"
	Pending    AppPkgOperationState = "pending"
	Processing AppPkgOperationState = "processing"
)

// Defines values for AppPkgSummarySourceType.
const (
	AppPkgSummarySourceTypeGITREPO AppPkgSummarySourceType = "GIT_REPO"
)

// APIResponse defines model for APIResponse.
type APIResponse struct {
	// RequestId Unique identifier for the request
	RequestId string `json:"requestId"`

	// Timestamp Timestamp of the response in ISO 8601 format
	Timestamp time.Time `json:"timestamp"`
}

// AppPkg Complete application package information
type AppPkg struct {
	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// Description Package description
	Description *string `json:"description,omitempty"`

	// Id Unique identifier for the application package
	Id string `json:"id"`

	// Name Application package name
	Name string `json:"name"`

	// Operation Current application package operation
	Operation AppPkgOperation `json:"operation"`

	// OperationContextualInfo Any contextual information related to operation, if available, is part of this variable
	OperationContextualInfo *string `json:"operationContextualInfo,omitempty"`

	// OperationState Current state of the application package operation
	OperationState AppPkgOperationState `json:"operationState"`

	// Source Source configuration based on sourceType
	Source AppPkg_Source `json:"source"`

	// SourceType Type of source for the application package
	SourceType AppPkgSourceType `json:"sourceType"`

	// UpdatedAt Last update timestamp
	UpdatedAt time.Time `json:"updatedAt"`

	// Version Application package version (semantic versioning)
	Version string `json:"version"`
}

// AppPkg_Source Source configuration based on sourceType
type AppPkg_Source struct {
	union json.RawMessage
}

// AppPkgSourceType Type of source for the application package
type AppPkgSourceType string

// AppPkgOnboardingReq defines model for AppPkgOnboardingReq.
type AppPkgOnboardingReq struct {
	// Name Application package name
	Name string `json:"name"`

	// Source Source configuration based on sourceType
	Source AppPkgOnboardingReq_Source `json:"source"`

	// SourceType Type of source for the application package
	SourceType AppPkgOnboardingReqSourceType `json:"sourceType"`
}

// AppPkgOnboardingReq_Source Source configuration based on sourceType
type AppPkgOnboardingReq_Source struct {
	union json.RawMessage
}

// AppPkgOnboardingReqSourceType Type of source for the application package
type AppPkgOnboardingReqSourceType string

// AppPkgOnboardingResp defines model for AppPkgOnboardingResp.
type AppPkgOnboardingResp struct {
	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// Id Unique identifier for the application package
	Id string `json:"id"`

	// Name Application name
	Name string `json:"name"`

	// Operation Current application package operation
	Operation AppPkgOperation `json:"operation"`

	// OperationContextualInfo Any contextual information related to operation, if available, is part of this variable
	OperationContextualInfo *string `json:"operationContextualInfo,omitempty"`

	// OperationState Current state of the application package operation
	OperationState AppPkgOperationState `json:"operationState"`

	// Source Source configuration based on sourceType
	Source AppPkgOnboardingResp_Source `json:"source"`

	// SourceType Type of source for the application package
	SourceType AppPkgOnboardingRespSourceType `json:"sourceType"`

	// UpdatedAt Last update timestamp
	UpdatedAt time.Time `json:"updatedAt"`

	// Version Application version
	Version string `json:"version"`
}

// AppPkgOnboardingResp_Source Source configuration based on sourceType
type AppPkgOnboardingResp_Source struct {
	union json.RawMessage
}

// AppPkgOnboardingRespSourceType Type of source for the application package
type AppPkgOnboardingRespSourceType string

// AppPkgOperation Current application package operation
type AppPkgOperation string

// AppPkgOperationState Current state of the application package operation
type AppPkgOperationState string

// AppPkgOperationStatus defines model for AppPkgOperationStatus.
type AppPkgOperationStatus struct {
	// CompletedAt When the operation completed (if applicable)
	CompletedAt *time.Time `json:"completedAt,omitempty"`

	// Error Error message if operation failed
	Error *string `json:"error,omitempty"`

	// Id Application package identifier
	Id string `json:"id"`

	// Message Current operation status message
	Message *string `json:"message,omitempty"`

	// Operation Current application package operation
	Operation AppPkgOperation `json:"operation"`

	// OperationState Current state of the application package operation
	OperationState AppPkgOperationState `json:"operationState"`

	// StartedAt When the operation started
	StartedAt time.Time `json:"startedAt"`
}

// AppPkgSummary defines model for AppPkgSummary.
type AppPkgSummary struct {
	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// Id Unique identifier for the application package
	Id string `json:"id"`

	// Name Application name
	Name string `json:"name"`

	// Operation Current application package operation
	Operation AppPkgOperation `json:"operation"`

	// OperationContextualInfo Any contextual information related to operation, if available, is part of this variable
	OperationContextualInfo *string `json:"operationContextualInfo,omitempty"`

	// OperationState Current state of the application package operation
	OperationState AppPkgOperationState `json:"operationState"`

	// Source Source configuration based on sourceType
	Source AppPkgSummary_Source `json:"source"`

	// SourceType Type of source for the application package
	SourceType AppPkgSummarySourceType `json:"sourceType"`

	// UpdatedAt Last update timestamp
	UpdatedAt time.Time `json:"updatedAt"`

	// Version Application version
	Version string `json:"version"`
}

// AppPkgSummary_Source Source configuration based on sourceType
type AppPkgSummary_Source struct {
	union json.RawMessage
}

// AppPkgSummarySourceType Type of source for the application package
type AppPkgSummarySourceType string

// DeleteAppPkgResp defines model for DeleteAppPkgResp.
type DeleteAppPkgResp struct {
	// Id Unique identifier for the deleted application package
	Id string `json:"id"`

	// Message Deletion status message
	Message *string `json:"message,omitempty"`

	// Operation Current application package operation
	Operation AppPkgOperation `json:"operation"`

	// OperationState Current state of the application package operation
	OperationState AppPkgOperationState `json:"operationState"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Details Additional error details
	Details *map[string]interface{} `json:"details,omitempty"`

	// ErrorCode Machine-readable error code
	ErrorCode string `json:"errorCode"`

	// RequestId Unique identifier for the request
	RequestId string `json:"requestId"`

	// Timestamp Timestamp of the response in ISO 8601 format
	Timestamp time.Time `json:"timestamp"`
}

// GitRepo Git repository source configuration
type GitRepo struct {
	// AccessToken Git access token for authentication
	AccessToken *string `json:"accessToken,omitempty"`

	// Branch Git branch to use
	Branch *string `json:"branch,omitempty"`

	// SubPath Subdirectory within the repository containing the application description yaml (ex margo.yaml)
	SubPath *string `json:"subPath,omitempty"`

	// Tag Git tag to use (alternative to branch)
	Tag *string `json:"tag,omitempty"`

	// Url Git repository URL (only HTTPS is supported)
	Url string `json:"url"`

	// Username Git username for authentication
	Username *string `json:"username,omitempty"`
	union    json.RawMessage
}

// GitRepo0 defines model for .
type GitRepo0 = interface{}

// GitRepo1 defines model for .
type GitRepo1 = interface{}

// ListAppPkgsResp defines model for ListAppPkgsResp.
type ListAppPkgsResp struct {
	// AppPkgs List of application packages
	AppPkgs    []AppPkgSummary    `json:"appPkgs"`
	Pagination PaginationResponse `json:"pagination"`
}

// PaginationResponse defines model for PaginationResponse.
type PaginationResponse struct {
	// Page Current page number
	Page int `json:"page"`

	// PageSize Number of items per page
	PageSize int `json:"pageSize"`

	// TotalItems Total number of items
	TotalItems int `json:"totalItems"`

	// TotalPages Total number of pages
	TotalPages int `json:"totalPages"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	// Field Field that failed validation
	Field string `json:"field"`

	// Message Validation error message
	Message string `json:"message"`
}

// ListAppPkgsParams defines parameters for ListAppPkgs.
type ListAppPkgsParams struct {
	// Page Page number (1-based)
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of items per page
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// DeleteAppPkgParams defines parameters for DeleteAppPkg.
type DeleteAppPkgParams struct {
	// Force Force deletion even if package is in use (may cause service disruption)
	Force *bool `form:"force,omitempty" json:"force,omitempty"`
}

// OnboardAppPkgJSONRequestBody defines body for OnboardAppPkg for application/json ContentType.
type OnboardAppPkgJSONRequestBody = AppPkgOnboardingReq

// AsGitRepo returns the union data inside the AppPkg_Source as a GitRepo
func (t AppPkg_Source) AsGitRepo() (GitRepo, error) {
	var body GitRepo
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGitRepo overwrites any union data inside the AppPkg_Source as the provided GitRepo
func (t *AppPkg_Source) FromGitRepo(v GitRepo) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGitRepo performs a merge with any union data inside the AppPkg_Source, using the provided GitRepo
func (t *AppPkg_Source) MergeGitRepo(v GitRepo) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t AppPkg_Source) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AppPkg_Source) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsGitRepo returns the union data inside the AppPkgOnboardingReq_Source as a GitRepo
func (t AppPkgOnboardingReq_Source) AsGitRepo() (GitRepo, error) {
	var body GitRepo
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGitRepo overwrites any union data inside the AppPkgOnboardingReq_Source as the provided GitRepo
func (t *AppPkgOnboardingReq_Source) FromGitRepo(v GitRepo) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGitRepo performs a merge with any union data inside the AppPkgOnboardingReq_Source, using the provided GitRepo
func (t *AppPkgOnboardingReq_Source) MergeGitRepo(v GitRepo) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t AppPkgOnboardingReq_Source) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AppPkgOnboardingReq_Source) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsGitRepo returns the union data inside the AppPkgOnboardingResp_Source as a GitRepo
func (t AppPkgOnboardingResp_Source) AsGitRepo() (GitRepo, error) {
	var body GitRepo
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGitRepo overwrites any union data inside the AppPkgOnboardingResp_Source as the provided GitRepo
func (t *AppPkgOnboardingResp_Source) FromGitRepo(v GitRepo) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGitRepo performs a merge with any union data inside the AppPkgOnboardingResp_Source, using the provided GitRepo
func (t *AppPkgOnboardingResp_Source) MergeGitRepo(v GitRepo) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t AppPkgOnboardingResp_Source) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AppPkgOnboardingResp_Source) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsGitRepo returns the union data inside the AppPkgSummary_Source as a GitRepo
func (t AppPkgSummary_Source) AsGitRepo() (GitRepo, error) {
	var body GitRepo
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGitRepo overwrites any union data inside the AppPkgSummary_Source as the provided GitRepo
func (t *AppPkgSummary_Source) FromGitRepo(v GitRepo) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGitRepo performs a merge with any union data inside the AppPkgSummary_Source, using the provided GitRepo
func (t *AppPkgSummary_Source) MergeGitRepo(v GitRepo) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t AppPkgSummary_Source) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AppPkgSummary_Source) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsGitRepo0 returns the union data inside the GitRepo as a GitRepo0
func (t GitRepo) AsGitRepo0() (GitRepo0, error) {
	var body GitRepo0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGitRepo0 overwrites any union data inside the GitRepo as the provided GitRepo0
func (t *GitRepo) FromGitRepo0(v GitRepo0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGitRepo0 performs a merge with any union data inside the GitRepo, using the provided GitRepo0
func (t *GitRepo) MergeGitRepo0(v GitRepo0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsGitRepo1 returns the union data inside the GitRepo as a GitRepo1
func (t GitRepo) AsGitRepo1() (GitRepo1, error) {
	var body GitRepo1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGitRepo1 overwrites any union data inside the GitRepo as the provided GitRepo1
func (t *GitRepo) FromGitRepo1(v GitRepo1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGitRepo1 performs a merge with any union data inside the GitRepo, using the provided GitRepo1
func (t *GitRepo) MergeGitRepo1(v GitRepo1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t GitRepo) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.AccessToken != nil {
		object["accessToken"], err = json.Marshal(t.AccessToken)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'accessToken': %w", err)
		}
	}

	if t.Branch != nil {
		object["branch"], err = json.Marshal(t.Branch)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'branch': %w", err)
		}
	}

	if t.SubPath != nil {
		object["subPath"], err = json.Marshal(t.SubPath)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'subPath': %w", err)
		}
	}

	if t.Tag != nil {
		object["tag"], err = json.Marshal(t.Tag)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'tag': %w", err)
		}
	}

	object["url"], err = json.Marshal(t.Url)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'url': %w", err)
	}

	if t.Username != nil {
		object["username"], err = json.Marshal(t.Username)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'username': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *GitRepo) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["accessToken"]; found {
		err = json.Unmarshal(raw, &t.AccessToken)
		if err != nil {
			return fmt.Errorf("error reading 'accessToken': %w", err)
		}
	}

	if raw, found := object["branch"]; found {
		err = json.Unmarshal(raw, &t.Branch)
		if err != nil {
			return fmt.Errorf("error reading 'branch': %w", err)
		}
	}

	if raw, found := object["subPath"]; found {
		err = json.Unmarshal(raw, &t.SubPath)
		if err != nil {
			return fmt.Errorf("error reading 'subPath': %w", err)
		}
	}

	if raw, found := object["tag"]; found {
		err = json.Unmarshal(raw, &t.Tag)
		if err != nil {
			return fmt.Errorf("error reading 'tag': %w", err)
		}
	}

	if raw, found := object["url"]; found {
		err = json.Unmarshal(raw, &t.Url)
		if err != nil {
			return fmt.Errorf("error reading 'url': %w", err)
		}
	}

	if raw, found := object["username"]; found {
		err = json.Unmarshal(raw, &t.Username)
		if err != nil {
			return fmt.Errorf("error reading 'username': %w", err)
		}
	}

	return err
}
